apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus.name" . }}
  namespace: {{ include "prometheus.namespace" (dict "key" "observability" "default" "ee-observability" "Values" .Values) }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}