# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emotion_llm.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'emotion_llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65motion_llm.proto\x12\x0e\x65motion_llm.v1\"C\n\x0e\x41nalyzeRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\x90\x01\n\x0f\x41nalyzeResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x17\n\x0fprimary_emotion\x18\x02 \x01(\t\x12\x17\n\x0fsentiment_score\x18\x03 \x01(\x01\x12\x12\n\nconfidence\x18\x04 \x01(\x01\x12\r\n\x05model\x18\x05 \x01(\t\x12\x14\n\x0craw_response\x18\x06 \x01(\t\"U\n\x13\x41nalyzeBatchRequest\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x1e.emotion_llm.v1.AnalyzeRequest\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xb7\x01\n\x11\x45motionLLMService\x12J\n\x07\x41nalyze\x12\x1e.emotion_llm.v1.AnalyzeRequest\x1a\x1f.emotion_llm.v1.AnalyzeResponse\x12V\n\x0c\x41nalyzeBatch\x12#.emotion_llm.v1.AnalyzeBatchRequest\x1a\x1f.emotion_llm.v1.AnalyzeResponse0\x01\x42/Z-github.com/emotion-echo/shared/pkg/emotionllmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/emotion-echo/shared/pkg/emotionllm'
  _globals['_ANALYZEREQUEST']._serialized_start=37
  _globals['_ANALYZEREQUEST']._serialized_end=104
  _globals['_ANALYZERESPONSE']._serialized_start=107
  _globals['_ANALYZERESPONSE']._serialized_end=251
  _globals['_ANALYZEBATCHREQUEST']._serialized_start=253
  _globals['_ANALYZEBATCHREQUEST']._serialized_end=338
  _globals['_EMOTIONLLMSERVICE']._serialized_start=341
  _globals['_EMOTIONLLMSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
