# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import emotion_llm_pb2 as emotion__llm__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in emotion_llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmotionLLMServiceStub:
    """EmotionLLMService 是 ai-svc 调用 emotion-llm-service 的契约

    之前是 HTTP（ai-svc.HTTPAnalyzer → POST /analyze）。
    升级为 gRPC 后更高效（HTTP/2 streaming + protobuf 强契约）。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/emotion_llm.v1.EmotionLLMService/Analyze',
                request_serializer=emotion__llm__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=emotion__llm__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.AnalyzeBatch = channel.unary_stream(
                '/emotion_llm.v1.EmotionLLMService/AnalyzeBatch',
                request_serializer=emotion__llm__pb2.AnalyzeBatchRequest.SerializeToString,
                response_deserializer=emotion__llm__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.ChatCompletion = channel.unary_stream(
                '/emotion_llm.v1.EmotionLLMService/ChatCompletion',
                request_serializer=emotion__llm__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=emotion__llm__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.ClassifyIntent = channel.unary_unary(
                '/emotion_llm.v1.EmotionLLMService/ClassifyIntent',
                request_serializer=emotion__llm__pb2.ClassifyIntentRequest.SerializeToString,
                response_deserializer=emotion__llm__pb2.IntentResult.FromString,
                _registered_method=True)


class EmotionLLMServiceServicer:
    """EmotionLLMService 是 ai-svc 调用 emotion-llm-service 的契约

    之前是 HTTP（ai-svc.HTTPAnalyzer → POST /analyze）。
    升级为 gRPC 后更高效（HTTP/2 streaming + protobuf 强契约）。
    """

    def Analyze(self, request, context):
        """Analyze 单条消息情绪分析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeBatch(self, request, context):
        """AnalyzeBatch 批量分析（server stream，Stage 16）

        适用：AI 一次推多条消息，server 流式返回每条结果（首字节延迟低）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatCompletion(self, request, context):
        """ChatCompletion 流式对话（Stage 80 · llm-chat-real-pipeline PR-1）

        OpenAI chat.completions 兼容语义：消息数组入、增量 chunk 流出。
        上游 LLM 由 env 决定（LLM_BASE_URL/LLM_API_KEY/LLM_MODEL，DeepSeek 等
        OpenAI 兼容端点）；无 key 或上游失败时降级内置 mock 文案（fallback_reason 非空），
        保证 CI / 离线 demo 全链路可跑（§契约 6 同款哲学）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyIntent(self, request, context):
        """ClassifyIntent 消息意图分类（Stage 82 · PR-3a）

        规则式 6 分类（emotional_support/study_help/tech_help/career_help/lifestyle/other），
        与情绪分析同款关键词打分风格——无 LLM 依赖、确定性可测。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmotionLLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=emotion__llm__pb2.AnalyzeRequest.FromString,
                    response_serializer=emotion__llm__pb2.AnalyzeResponse.SerializeToString,
            ),
            'AnalyzeBatch': grpc.unary_stream_rpc_method_handler(
                    servicer.AnalyzeBatch,
                    request_deserializer=emotion__llm__pb2.AnalyzeBatchRequest.FromString,
                    response_serializer=emotion__llm__pb2.AnalyzeResponse.SerializeToString,
            ),
            'ChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=emotion__llm__pb2.ChatCompletionRequest.FromString,
                    response_serializer=emotion__llm__pb2.ChatChunk.SerializeToString,
            ),
            'ClassifyIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyIntent,
                    request_deserializer=emotion__llm__pb2.ClassifyIntentRequest.FromString,
                    response_serializer=emotion__llm__pb2.IntentResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotion_llm.v1.EmotionLLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emotion_llm.v1.EmotionLLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmotionLLMService:
    """EmotionLLMService 是 ai-svc 调用 emotion-llm-service 的契约

    之前是 HTTP（ai-svc.HTTPAnalyzer → POST /analyze）。
    升级为 gRPC 后更高效（HTTP/2 streaming + protobuf 强契约）。
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion_llm.v1.EmotionLLMService/Analyze',
            emotion__llm__pb2.AnalyzeRequest.SerializeToString,
            emotion__llm__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emotion_llm.v1.EmotionLLMService/AnalyzeBatch',
            emotion__llm__pb2.AnalyzeBatchRequest.SerializeToString,
            emotion__llm__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emotion_llm.v1.EmotionLLMService/ChatCompletion',
            emotion__llm__pb2.ChatCompletionRequest.SerializeToString,
            emotion__llm__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion_llm.v1.EmotionLLMService/ClassifyIntent',
            emotion__llm__pb2.ClassifyIntentRequest.SerializeToString,
            emotion__llm__pb2.IntentResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
