// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: emotion_query.proto

package emotionquery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmotionQueryService_GetEmotionByMessage_FullMethodName      = "/emotion_ai.v1.EmotionQueryService/GetEmotionByMessage"
	EmotionQueryService_GetEmotionByConversation_FullMethodName = "/emotion_ai.v1.EmotionQueryService/GetEmotionByConversation"
	EmotionQueryService_GetFusedEmotion_FullMethodName          = "/emotion_ai.v1.EmotionQueryService/GetFusedEmotion"
	EmotionQueryService_UpsertNeutralEmotion_FullMethodName     = "/emotion_ai.v1.EmotionQueryService/UpsertNeutralEmotion"
	EmotionQueryService_MultiModalAnalyze_FullMethodName        = "/emotion_ai.v1.EmotionQueryService/MultiModalAnalyze"
	EmotionQueryService_SynthesizeSpeech_FullMethodName         = "/emotion_ai.v1.EmotionQueryService/SynthesizeSpeech"
	EmotionQueryService_AIHealth_FullMethodName                 = "/emotion_ai.v1.EmotionQueryService/AIHealth"
)

// EmotionQueryServiceClient is the client API for EmotionQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmotionQueryService 是 ai-svc 暴露给其他内部服务的查询接口（Stage 19）
//
// 之前只能通过 HTTP 调（ai-svc Gin server :8891）
// 现在多一个 gRPC 接口（ai-svc gRPC server :8892）
// 两种协议同时存在，前端继续用 HTTP，内部 svc-to-svc 用 gRPC
//
// Stage 34: 新增 GetFusedEmotion（多模态融合产物查询）
// Stage 36-A3: 新增 UpsertNeutralEmotion（chat-svc 同步 fallback 写入中性占位情绪）
type EmotionQueryServiceClient interface {
	// GetEmotionByMessage 根据 message_id 查情绪
	GetEmotionByMessage(ctx context.Context, in *GetEmotionByMessageRequest, opts ...grpc.CallOption) (*Emotion, error)
	// GetEmotionByConversation 根据 conversation_id 查情绪列表
	GetEmotionByConversation(ctx context.Context, in *GetEmotionByConversationRequest, opts ...grpc.CallOption) (*EmotionList, error)
	// GetFusedEmotion 根据 message_id 查多模态融合产物（Stage 34）
	GetFusedEmotion(ctx context.Context, in *GetFusedEmotionRequest, opts ...grpc.CallOption) (*FusedEmotion, error)
	// UpsertNeutralEmotion 写入一条中性情绪占位（Stage 36-A3 / G4）
	//
	// 设计动机：Kafka 关闭时（KAFKA_ENABLED=false / dev 模式），chat-svc 发消息后
	// 不会经过 Kafka → ai-svc 永远不会写入 emotion_analysis 行，导致前端"情绪分析"
	// 功能在 dev 模式下完全无数据。本 RPC 让 chat-svc 在 send message 成功后
	// 同步调用 ai-svc，ai-svc 写入中性占位情绪（primary_emotion="neutral",
	// sentiment_score=0, confidence=0, model="sync-fallback"）。
	//
	// 幂等：使用 event_id 作为唯一键（DB UNIQUE 约束）。chat-svc 传其 outbox
	// event UUID；重复调用返回 OK 不重复落库（on conflict do nothing）。
	//
	// 错误语义：
	//   - message_id<=0 / user_id<=0 → InvalidArgument
	//   - 写入失败 → Internal
	//   - 成功 → 返回写入（或已存在）的 emotion_analysis 行 id
	UpsertNeutralEmotion(ctx context.Context, in *UpsertNeutralEmotionRequest, opts ...grpc.CallOption) (*UpsertNeutralEmotionResponse, error)
	// MultiModalAnalyze 多模态情绪/语音/图像分析（Sprint F2 2026-09-11）
	//
	// 与 HTTP `POST /api/v1/multimodal/analyze` 语义对齐（multipart/form-data 转 bytes）。
	// 内部 svc-to-svc（BFF → ai-svc）走 gRPC；外部前端继续走 HTTP。
	//
	// 错误语义：
	//   - kind 非法 / file 缺失（kind!=text） → InvalidArgument
	//   - 上游 FER/SenseVoice/XTTS 不可用 → Unavailable（与 HTTP 503 对齐）
	//   - 其他 → Internal
	MultiModalAnalyze(ctx context.Context, in *MultiModalAnalyzeRequest, opts ...grpc.CallOption) (*MultiModalAnalyzeResponse, error)
	// SynthesizeSpeech TTS 语音合成（Sprint F2 2026-09-11）
	//
	// 与 HTTP `POST /api/v1/tts/synthesize` 语义对齐。
	// 错误语义：XTTS 未配置 / 上游不可用 → Unavailable；其他 → Internal。
	SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SynthesizeSpeechResponse, error)
	// AIHealth AI 服务集群健康探针（Sprint F2 2026-09-11）
	//
	// 与 HTTP `GET /api/v1/ai/health` 语义对齐。返回 FER/SenseVoice/XTTS
	// 各自 enabled/healthy 状态 + all_healthy 总标志。
	AIHealth(ctx context.Context, in *AIHealthRequest, opts ...grpc.CallOption) (*AIHealthResponse, error)
}

type emotionQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionQueryServiceClient(cc grpc.ClientConnInterface) EmotionQueryServiceClient {
	return &emotionQueryServiceClient{cc}
}

func (c *emotionQueryServiceClient) GetEmotionByMessage(ctx context.Context, in *GetEmotionByMessageRequest, opts ...grpc.CallOption) (*Emotion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Emotion)
	err := c.cc.Invoke(ctx, EmotionQueryService_GetEmotionByMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) GetEmotionByConversation(ctx context.Context, in *GetEmotionByConversationRequest, opts ...grpc.CallOption) (*EmotionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionList)
	err := c.cc.Invoke(ctx, EmotionQueryService_GetEmotionByConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) GetFusedEmotion(ctx context.Context, in *GetFusedEmotionRequest, opts ...grpc.CallOption) (*FusedEmotion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FusedEmotion)
	err := c.cc.Invoke(ctx, EmotionQueryService_GetFusedEmotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) UpsertNeutralEmotion(ctx context.Context, in *UpsertNeutralEmotionRequest, opts ...grpc.CallOption) (*UpsertNeutralEmotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertNeutralEmotionResponse)
	err := c.cc.Invoke(ctx, EmotionQueryService_UpsertNeutralEmotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) MultiModalAnalyze(ctx context.Context, in *MultiModalAnalyzeRequest, opts ...grpc.CallOption) (*MultiModalAnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiModalAnalyzeResponse)
	err := c.cc.Invoke(ctx, EmotionQueryService_MultiModalAnalyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SynthesizeSpeechResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizeSpeechResponse)
	err := c.cc.Invoke(ctx, EmotionQueryService_SynthesizeSpeech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) AIHealth(ctx context.Context, in *AIHealthRequest, opts ...grpc.CallOption) (*AIHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIHealthResponse)
	err := c.cc.Invoke(ctx, EmotionQueryService_AIHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmotionQueryServiceServer is the server API for EmotionQueryService service.
// All implementations must embed UnimplementedEmotionQueryServiceServer
// for forward compatibility.
//
// EmotionQueryService 是 ai-svc 暴露给其他内部服务的查询接口（Stage 19）
//
// 之前只能通过 HTTP 调（ai-svc Gin server :8891）
// 现在多一个 gRPC 接口（ai-svc gRPC server :8892）
// 两种协议同时存在，前端继续用 HTTP，内部 svc-to-svc 用 gRPC
//
// Stage 34: 新增 GetFusedEmotion（多模态融合产物查询）
// Stage 36-A3: 新增 UpsertNeutralEmotion（chat-svc 同步 fallback 写入中性占位情绪）
type EmotionQueryServiceServer interface {
	// GetEmotionByMessage 根据 message_id 查情绪
	GetEmotionByMessage(context.Context, *GetEmotionByMessageRequest) (*Emotion, error)
	// GetEmotionByConversation 根据 conversation_id 查情绪列表
	GetEmotionByConversation(context.Context, *GetEmotionByConversationRequest) (*EmotionList, error)
	// GetFusedEmotion 根据 message_id 查多模态融合产物（Stage 34）
	GetFusedEmotion(context.Context, *GetFusedEmotionRequest) (*FusedEmotion, error)
	// UpsertNeutralEmotion 写入一条中性情绪占位（Stage 36-A3 / G4）
	//
	// 设计动机：Kafka 关闭时（KAFKA_ENABLED=false / dev 模式），chat-svc 发消息后
	// 不会经过 Kafka → ai-svc 永远不会写入 emotion_analysis 行，导致前端"情绪分析"
	// 功能在 dev 模式下完全无数据。本 RPC 让 chat-svc 在 send message 成功后
	// 同步调用 ai-svc，ai-svc 写入中性占位情绪（primary_emotion="neutral",
	// sentiment_score=0, confidence=0, model="sync-fallback"）。
	//
	// 幂等：使用 event_id 作为唯一键（DB UNIQUE 约束）。chat-svc 传其 outbox
	// event UUID；重复调用返回 OK 不重复落库（on conflict do nothing）。
	//
	// 错误语义：
	//   - message_id<=0 / user_id<=0 → InvalidArgument
	//   - 写入失败 → Internal
	//   - 成功 → 返回写入（或已存在）的 emotion_analysis 行 id
	UpsertNeutralEmotion(context.Context, *UpsertNeutralEmotionRequest) (*UpsertNeutralEmotionResponse, error)
	// MultiModalAnalyze 多模态情绪/语音/图像分析（Sprint F2 2026-09-11）
	//
	// 与 HTTP `POST /api/v1/multimodal/analyze` 语义对齐（multipart/form-data 转 bytes）。
	// 内部 svc-to-svc（BFF → ai-svc）走 gRPC；外部前端继续走 HTTP。
	//
	// 错误语义：
	//   - kind 非法 / file 缺失（kind!=text） → InvalidArgument
	//   - 上游 FER/SenseVoice/XTTS 不可用 → Unavailable（与 HTTP 503 对齐）
	//   - 其他 → Internal
	MultiModalAnalyze(context.Context, *MultiModalAnalyzeRequest) (*MultiModalAnalyzeResponse, error)
	// SynthesizeSpeech TTS 语音合成（Sprint F2 2026-09-11）
	//
	// 与 HTTP `POST /api/v1/tts/synthesize` 语义对齐。
	// 错误语义：XTTS 未配置 / 上游不可用 → Unavailable；其他 → Internal。
	SynthesizeSpeech(context.Context, *SynthesizeSpeechRequest) (*SynthesizeSpeechResponse, error)
	// AIHealth AI 服务集群健康探针（Sprint F2 2026-09-11）
	//
	// 与 HTTP `GET /api/v1/ai/health` 语义对齐。返回 FER/SenseVoice/XTTS
	// 各自 enabled/healthy 状态 + all_healthy 总标志。
	AIHealth(context.Context, *AIHealthRequest) (*AIHealthResponse, error)
	mustEmbedUnimplementedEmotionQueryServiceServer()
}

// UnimplementedEmotionQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionQueryServiceServer struct{}

func (UnimplementedEmotionQueryServiceServer) GetEmotionByMessage(context.Context, *GetEmotionByMessageRequest) (*Emotion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmotionByMessage not implemented")
}
func (UnimplementedEmotionQueryServiceServer) GetEmotionByConversation(context.Context, *GetEmotionByConversationRequest) (*EmotionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmotionByConversation not implemented")
}
func (UnimplementedEmotionQueryServiceServer) GetFusedEmotion(context.Context, *GetFusedEmotionRequest) (*FusedEmotion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFusedEmotion not implemented")
}
func (UnimplementedEmotionQueryServiceServer) UpsertNeutralEmotion(context.Context, *UpsertNeutralEmotionRequest) (*UpsertNeutralEmotionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertNeutralEmotion not implemented")
}
func (UnimplementedEmotionQueryServiceServer) MultiModalAnalyze(context.Context, *MultiModalAnalyzeRequest) (*MultiModalAnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MultiModalAnalyze not implemented")
}
func (UnimplementedEmotionQueryServiceServer) SynthesizeSpeech(context.Context, *SynthesizeSpeechRequest) (*SynthesizeSpeechResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SynthesizeSpeech not implemented")
}
func (UnimplementedEmotionQueryServiceServer) AIHealth(context.Context, *AIHealthRequest) (*AIHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AIHealth not implemented")
}
func (UnimplementedEmotionQueryServiceServer) mustEmbedUnimplementedEmotionQueryServiceServer() {}
func (UnimplementedEmotionQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeEmotionQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionQueryServiceServer will
// result in compilation errors.
type UnsafeEmotionQueryServiceServer interface {
	mustEmbedUnimplementedEmotionQueryServiceServer()
}

func RegisterEmotionQueryServiceServer(s grpc.ServiceRegistrar, srv EmotionQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedEmotionQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionQueryService_ServiceDesc, srv)
}

func _EmotionQueryService_GetEmotionByMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmotionByMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).GetEmotionByMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_GetEmotionByMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).GetEmotionByMessage(ctx, req.(*GetEmotionByMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_GetEmotionByConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmotionByConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).GetEmotionByConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_GetEmotionByConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).GetEmotionByConversation(ctx, req.(*GetEmotionByConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_GetFusedEmotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFusedEmotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).GetFusedEmotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_GetFusedEmotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).GetFusedEmotion(ctx, req.(*GetFusedEmotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_UpsertNeutralEmotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNeutralEmotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).UpsertNeutralEmotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_UpsertNeutralEmotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).UpsertNeutralEmotion(ctx, req.(*UpsertNeutralEmotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_MultiModalAnalyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiModalAnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).MultiModalAnalyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_MultiModalAnalyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).MultiModalAnalyze(ctx, req.(*MultiModalAnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_SynthesizeSpeech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).SynthesizeSpeech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_SynthesizeSpeech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).SynthesizeSpeech(ctx, req.(*SynthesizeSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_AIHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).AIHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_AIHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).AIHealth(ctx, req.(*AIHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmotionQueryService_ServiceDesc is the grpc.ServiceDesc for EmotionQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_ai.v1.EmotionQueryService",
	HandlerType: (*EmotionQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmotionByMessage",
			Handler:    _EmotionQueryService_GetEmotionByMessage_Handler,
		},
		{
			MethodName: "GetEmotionByConversation",
			Handler:    _EmotionQueryService_GetEmotionByConversation_Handler,
		},
		{
			MethodName: "GetFusedEmotion",
			Handler:    _EmotionQueryService_GetFusedEmotion_Handler,
		},
		{
			MethodName: "UpsertNeutralEmotion",
			Handler:    _EmotionQueryService_UpsertNeutralEmotion_Handler,
		},
		{
			MethodName: "MultiModalAnalyze",
			Handler:    _EmotionQueryService_MultiModalAnalyze_Handler,
		},
		{
			MethodName: "SynthesizeSpeech",
			Handler:    _EmotionQueryService_SynthesizeSpeech_Handler,
		},
		{
			MethodName: "AIHealth",
			Handler:    _EmotionQueryService_AIHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emotion_query.proto",
}
