// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: emotion_query.proto

package emotionquery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Emotion 单条消息的情绪数据
type Emotion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId      int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PrimaryEmotion string                 `protobuf:"bytes,4,opt,name=primary_emotion,json=primaryEmotion,proto3" json:"primary_emotion,omitempty"`   // happy/sad/anxious/angry/calm...
	SentimentScore float64                `protobuf:"fixed64,5,opt,name=sentiment_score,json=sentimentScore,proto3" json:"sentiment_score,omitempty"` // -1.0 ~ 1.0
	Confidence     float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Model          string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAtMs    int64                  `protobuf:"varint,8,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"` // 毫秒时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Emotion) Reset() {
	*x = Emotion{}
	mi := &file_emotion_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emotion) ProtoMessage() {}

func (x *Emotion) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emotion.ProtoReflect.Descriptor instead.
func (*Emotion) Descriptor() ([]byte, []int) {
	return file_emotion_query_proto_rawDescGZIP(), []int{0}
}

func (x *Emotion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Emotion) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Emotion) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Emotion) GetPrimaryEmotion() string {
	if x != nil {
		return x.PrimaryEmotion
	}
	return ""
}

func (x *Emotion) GetSentimentScore() float64 {
	if x != nil {
		return x.SentimentScore
	}
	return 0
}

func (x *Emotion) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Emotion) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Emotion) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

// GetEmotionByMessage 请求
type GetEmotionByMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmotionByMessageRequest) Reset() {
	*x = GetEmotionByMessageRequest{}
	mi := &file_emotion_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmotionByMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmotionByMessageRequest) ProtoMessage() {}

func (x *GetEmotionByMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmotionByMessageRequest.ProtoReflect.Descriptor instead.
func (*GetEmotionByMessageRequest) Descriptor() ([]byte, []int) {
	return file_emotion_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmotionByMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// GetEmotionByConversation 请求
type GetEmotionByConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 可选，默认 50
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEmotionByConversationRequest) Reset() {
	*x = GetEmotionByConversationRequest{}
	mi := &file_emotion_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmotionByConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmotionByConversationRequest) ProtoMessage() {}

func (x *GetEmotionByConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmotionByConversationRequest.ProtoReflect.Descriptor instead.
func (*GetEmotionByConversationRequest) Descriptor() ([]byte, []int) {
	return file_emotion_query_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmotionByConversationRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetEmotionByConversationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// EmotionList 多条情绪
type EmotionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Emotion             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionList) Reset() {
	*x = EmotionList{}
	mi := &file_emotion_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionList) ProtoMessage() {}

func (x *EmotionList) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionList.ProtoReflect.Descriptor instead.
func (*EmotionList) Descriptor() ([]byte, []int) {
	return file_emotion_query_proto_rawDescGZIP(), []int{3}
}

func (x *EmotionList) GetItems() []*Emotion {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *EmotionList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_emotion_query_proto protoreflect.FileDescriptor

const file_emotion_query_proto_rawDesc = "" +
	"\n" +
	"\x13emotion_query.proto\x12\remotion_ai.v1\"\x8d\x02\n" +
	"\aEmotion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12'\n" +
	"\x0fprimary_emotion\x18\x04 \x01(\tR\x0eprimaryEmotion\x12'\n" +
	"\x0fsentiment_score\x18\x05 \x01(\x01R\x0esentimentScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\"\n" +
	"\rcreated_at_ms\x18\b \x01(\x03R\vcreatedAtMs\";\n" +
	"\x1aGetEmotionByMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"`\n" +
	"\x1fGetEmotionByConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Q\n" +
	"\vEmotionList\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.emotion_ai.v1.EmotionR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xd7\x01\n" +
	"\x13EmotionQueryService\x12X\n" +
	"\x13GetEmotionByMessage\x12).emotion_ai.v1.GetEmotionByMessageRequest\x1a\x16.emotion_ai.v1.Emotion\x12f\n" +
	"\x18GetEmotionByConversation\x12..emotion_ai.v1.GetEmotionByConversationRequest\x1a\x1a.emotion_ai.v1.EmotionListB1Z/github.com/emotion-echo/shared/pkg/emotionqueryb\x06proto3"

var (
	file_emotion_query_proto_rawDescOnce sync.Once
	file_emotion_query_proto_rawDescData []byte
)

func file_emotion_query_proto_rawDescGZIP() []byte {
	file_emotion_query_proto_rawDescOnce.Do(func() {
		file_emotion_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emotion_query_proto_rawDesc), len(file_emotion_query_proto_rawDesc)))
	})
	return file_emotion_query_proto_rawDescData
}

var file_emotion_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_emotion_query_proto_goTypes = []any{
	(*Emotion)(nil),                         // 0: emotion_ai.v1.Emotion
	(*GetEmotionByMessageRequest)(nil),      // 1: emotion_ai.v1.GetEmotionByMessageRequest
	(*GetEmotionByConversationRequest)(nil), // 2: emotion_ai.v1.GetEmotionByConversationRequest
	(*EmotionList)(nil),                     // 3: emotion_ai.v1.EmotionList
}
var file_emotion_query_proto_depIdxs = []int32{
	0, // 0: emotion_ai.v1.EmotionList.items:type_name -> emotion_ai.v1.Emotion
	1, // 1: emotion_ai.v1.EmotionQueryService.GetEmotionByMessage:input_type -> emotion_ai.v1.GetEmotionByMessageRequest
	2, // 2: emotion_ai.v1.EmotionQueryService.GetEmotionByConversation:input_type -> emotion_ai.v1.GetEmotionByConversationRequest
	0, // 3: emotion_ai.v1.EmotionQueryService.GetEmotionByMessage:output_type -> emotion_ai.v1.Emotion
	3, // 4: emotion_ai.v1.EmotionQueryService.GetEmotionByConversation:output_type -> emotion_ai.v1.EmotionList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_emotion_query_proto_init() }
func file_emotion_query_proto_init() {
	if File_emotion_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emotion_query_proto_rawDesc), len(file_emotion_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emotion_query_proto_goTypes,
		DependencyIndexes: file_emotion_query_proto_depIdxs,
		MessageInfos:      file_emotion_query_proto_msgTypes,
	}.Build()
	File_emotion_query_proto = out.File
	file_emotion_query_proto_goTypes = nil
	file_emotion_query_proto_depIdxs = nil
}
