// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: emotion_query.proto

package emotionquery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmotionQueryService_GetEmotionByMessage_FullMethodName      = "/emotion_ai.v1.EmotionQueryService/GetEmotionByMessage"
	EmotionQueryService_GetEmotionByConversation_FullMethodName = "/emotion_ai.v1.EmotionQueryService/GetEmotionByConversation"
)

// EmotionQueryServiceClient is the client API for EmotionQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmotionQueryService 是 ai-svc 暴露给其他内部服务的查询接口（Stage 19）
//
// 之前只能通过 HTTP 调（ai-svc Gin server :8891）
// 现在多一个 gRPC 接口（ai-svc gRPC server :8892）
// 两种协议同时存在，前端继续用 HTTP，内部 svc-to-svc 用 gRPC
type EmotionQueryServiceClient interface {
	// GetEmotionByMessage 根据 message_id 查情绪
	GetEmotionByMessage(ctx context.Context, in *GetEmotionByMessageRequest, opts ...grpc.CallOption) (*Emotion, error)
	// GetEmotionByConversation 根据 conversation_id 查情绪列表
	GetEmotionByConversation(ctx context.Context, in *GetEmotionByConversationRequest, opts ...grpc.CallOption) (*EmotionList, error)
}

type emotionQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionQueryServiceClient(cc grpc.ClientConnInterface) EmotionQueryServiceClient {
	return &emotionQueryServiceClient{cc}
}

func (c *emotionQueryServiceClient) GetEmotionByMessage(ctx context.Context, in *GetEmotionByMessageRequest, opts ...grpc.CallOption) (*Emotion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Emotion)
	err := c.cc.Invoke(ctx, EmotionQueryService_GetEmotionByMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionQueryServiceClient) GetEmotionByConversation(ctx context.Context, in *GetEmotionByConversationRequest, opts ...grpc.CallOption) (*EmotionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionList)
	err := c.cc.Invoke(ctx, EmotionQueryService_GetEmotionByConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmotionQueryServiceServer is the server API for EmotionQueryService service.
// All implementations must embed UnimplementedEmotionQueryServiceServer
// for forward compatibility.
//
// EmotionQueryService 是 ai-svc 暴露给其他内部服务的查询接口（Stage 19）
//
// 之前只能通过 HTTP 调（ai-svc Gin server :8891）
// 现在多一个 gRPC 接口（ai-svc gRPC server :8892）
// 两种协议同时存在，前端继续用 HTTP，内部 svc-to-svc 用 gRPC
type EmotionQueryServiceServer interface {
	// GetEmotionByMessage 根据 message_id 查情绪
	GetEmotionByMessage(context.Context, *GetEmotionByMessageRequest) (*Emotion, error)
	// GetEmotionByConversation 根据 conversation_id 查情绪列表
	GetEmotionByConversation(context.Context, *GetEmotionByConversationRequest) (*EmotionList, error)
	mustEmbedUnimplementedEmotionQueryServiceServer()
}

// UnimplementedEmotionQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionQueryServiceServer struct{}

func (UnimplementedEmotionQueryServiceServer) GetEmotionByMessage(context.Context, *GetEmotionByMessageRequest) (*Emotion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmotionByMessage not implemented")
}
func (UnimplementedEmotionQueryServiceServer) GetEmotionByConversation(context.Context, *GetEmotionByConversationRequest) (*EmotionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmotionByConversation not implemented")
}
func (UnimplementedEmotionQueryServiceServer) mustEmbedUnimplementedEmotionQueryServiceServer() {}
func (UnimplementedEmotionQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeEmotionQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionQueryServiceServer will
// result in compilation errors.
type UnsafeEmotionQueryServiceServer interface {
	mustEmbedUnimplementedEmotionQueryServiceServer()
}

func RegisterEmotionQueryServiceServer(s grpc.ServiceRegistrar, srv EmotionQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedEmotionQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionQueryService_ServiceDesc, srv)
}

func _EmotionQueryService_GetEmotionByMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmotionByMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).GetEmotionByMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_GetEmotionByMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).GetEmotionByMessage(ctx, req.(*GetEmotionByMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionQueryService_GetEmotionByConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmotionByConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionQueryServiceServer).GetEmotionByConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionQueryService_GetEmotionByConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionQueryServiceServer).GetEmotionByConversation(ctx, req.(*GetEmotionByConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmotionQueryService_ServiceDesc is the grpc.ServiceDesc for EmotionQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_ai.v1.EmotionQueryService",
	HandlerType: (*EmotionQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmotionByMessage",
			Handler:    _EmotionQueryService_GetEmotionByMessage_Handler,
		},
		{
			MethodName: "GetEmotionByConversation",
			Handler:    _EmotionQueryService_GetEmotionByConversation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emotion_query.proto",
}
