apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ee-data
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{- if and .Values.global .Values.global.secrets .Values.global.secrets.postgresPassword }}{{ .Values.global.secrets.postgresPassword }}{{- else }}postgres{{- end }}
  user: {{- if and .Values.global .Values.global.secrets .Values.global.secrets.postgresUser }}{{ .Values.global.secrets.postgresUser }}{{- else }}postgres{{- end }}