image:
  repository: crpi-rnawo8jx69bslvbx.cn-hongkong.personal.cr.aliyuncs.com/emotion-echo/fer-tflite
  tag: v0.1.0
  pullPolicy: IfNotPresent
replicas: 1
service:
  port: 8004
resources:
  requests: {cpu: 300m, memory: 384Mi}
  limits: {cpu: 1000m, memory: 1024Mi}