apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ include "loki.namespaceObservability" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 3100 }}
      targetPort: http
      protocol: TCP