apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-svc-config
  namespace: ee-app
  labels:
    {{- include "chat-svc.labels" . | nindent 4 }}
data:
  chat-api.yaml: |
    Name: chat-api
    Host: 0.0.0.0
    Port: 8890
    Log:
      Mode: json
      Level: info