apiVersion: v1
kind: Secret
metadata:
  name: chat-svc-secret
  namespace: ee-app
  labels:
    {{- include "chat-svc.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresDsn: "host=postgres.ee-data port=5432 user=postgres password=postgres dbname=emotion_echo sslmode=disable search_path=emotion_echo_chat"