apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc-client
      port: {{ .Values.service.grpcClientPort }}
      targetPort: grpc-client
    - name: grpc-server
      port: {{ .Values.service.grpcServerPort }}
      targetPort: grpc-server
  selector:
    app.kubernetes.io/name: {{ include "nacos.fullname" . }}
