// proto/chat_events.proto
//
// Stage 73：Kafka 事件 payload JSON → Protobuf 迁移（kafka-reliability-gaps.md §1.5/§3.5）
//
// 背景：
//   chat-svc → Kafka → analytics/ai 的事件链此前是 ad-hoc JSON
//   （chat-svc/internal/events/events.go 定义，analytics/ai 各自镜像），
//   schema 漂移已实际发生（Stage 37-A event_type 细分）。
//   本文件成为事件的单一事实源，生成代码归位 shared/pkg/chatevents。
//
// 兼容性策略（双写窗口）：
//   - producer（chat-svc KafkaEventPublisher）：Protobuf 序列化 + Kafka header
//     "content-type: application/x-protobuf"
//   - consumer（analytics/ai）：优先按 header 识别，否则嗅探首字节（'{' = 旧 JSON），
//     旧 JSON 消息在迁移窗口内继续可消费
//   - outbox_events.payload 列保持 JSONB（DB 内 JSON 是 outbox 自己的存储格式，
//     relay 出站时才转 Protobuf）
//
// event_type 命名契约（ADR-19 PR-A1.4 统一后）：
//   type 字段恒为带点原值：message.created / conversation.created / conversation.closed

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: chat_events.proto

package chatevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatEventEnvelope chat-svc 事件信封（对应 JSON 时代的 events.Event）
type ChatEventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件唯一标识（UUID v4），消费者幂等去重键；同 JSON 时代 events.Event.ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 事件类型（message.created / conversation.created / conversation.closed）
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// 事件源服务名
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// 事件产生时间（unix 毫秒；JSON 时代为 RFC3339 字符串，proto 用 int64 消除时区/格式歧义）
	TimeUnixMilli int64 `protobuf:"varint,4,opt,name=time_unix_milli,json=timeUnixMilli,proto3" json:"time_unix_milli,omitempty"`
	// 事件载荷，按 type 恰好设置其一
	//
	// Types that are valid to be assigned to Data:
	//
	//	*ChatEventEnvelope_MessageCreated
	//	*ChatEventEnvelope_ConversationCreated
	//	*ChatEventEnvelope_ConversationClosed
	Data          isChatEventEnvelope_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEventEnvelope) Reset() {
	*x = ChatEventEnvelope{}
	mi := &file_chat_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEventEnvelope) ProtoMessage() {}

func (x *ChatEventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_chat_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEventEnvelope.ProtoReflect.Descriptor instead.
func (*ChatEventEnvelope) Descriptor() ([]byte, []int) {
	return file_chat_events_proto_rawDescGZIP(), []int{0}
}

func (x *ChatEventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatEventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ChatEventEnvelope) GetTimeUnixMilli() int64 {
	if x != nil {
		return x.TimeUnixMilli
	}
	return 0
}

func (x *ChatEventEnvelope) GetData() isChatEventEnvelope_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatEventEnvelope) GetMessageCreated() *MessageCreatedData {
	if x != nil {
		if x, ok := x.Data.(*ChatEventEnvelope_MessageCreated); ok {
			return x.MessageCreated
		}
	}
	return nil
}

func (x *ChatEventEnvelope) GetConversationCreated() *ConversationCreatedData {
	if x != nil {
		if x, ok := x.Data.(*ChatEventEnvelope_ConversationCreated); ok {
			return x.ConversationCreated
		}
	}
	return nil
}

func (x *ChatEventEnvelope) GetConversationClosed() *ConversationClosedData {
	if x != nil {
		if x, ok := x.Data.(*ChatEventEnvelope_ConversationClosed); ok {
			return x.ConversationClosed
		}
	}
	return nil
}

type isChatEventEnvelope_Data interface {
	isChatEventEnvelope_Data()
}

type ChatEventEnvelope_MessageCreated struct {
	MessageCreated *MessageCreatedData `protobuf:"bytes,5,opt,name=message_created,json=messageCreated,proto3,oneof"`
}

type ChatEventEnvelope_ConversationCreated struct {
	ConversationCreated *ConversationCreatedData `protobuf:"bytes,6,opt,name=conversation_created,json=conversationCreated,proto3,oneof"`
}

type ChatEventEnvelope_ConversationClosed struct {
	ConversationClosed *ConversationClosedData `protobuf:"bytes,7,opt,name=conversation_closed,json=conversationClosed,proto3,oneof"`
}

func (*ChatEventEnvelope_MessageCreated) isChatEventEnvelope_Data() {}

func (*ChatEventEnvelope_ConversationCreated) isChatEventEnvelope_Data() {}

func (*ChatEventEnvelope_ConversationClosed) isChatEventEnvelope_Data() {}

// MessageCreatedData message.created 载荷
// ai-svc 读 content 做情绪分析；message_id 用于回填 emotion_analysis
type MessageCreatedData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageCreatedData) Reset() {
	*x = MessageCreatedData{}
	mi := &file_chat_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreatedData) ProtoMessage() {}

func (x *MessageCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreatedData.ProtoReflect.Descriptor instead.
func (*MessageCreatedData) Descriptor() ([]byte, []int) {
	return file_chat_events_proto_rawDescGZIP(), []int{1}
}

func (x *MessageCreatedData) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageCreatedData) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MessageCreatedData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageCreatedData) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageCreatedData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageCreatedData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ConversationCreatedData conversation.created 载荷
type ConversationCreatedData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationCreatedData) Reset() {
	*x = ConversationCreatedData{}
	mi := &file_chat_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationCreatedData) ProtoMessage() {}

func (x *ConversationCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationCreatedData.ProtoReflect.Descriptor instead.
func (*ConversationCreatedData) Descriptor() ([]byte, []int) {
	return file_chat_events_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationCreatedData) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ConversationCreatedData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConversationCreatedData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConversationCreatedData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ConversationClosedData conversation.closed 载荷
type ConversationClosedData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClosedAt       int64                  `protobuf:"varint,3,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationClosedData) Reset() {
	*x = ConversationClosedData{}
	mi := &file_chat_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationClosedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationClosedData) ProtoMessage() {}

func (x *ConversationClosedData) ProtoReflect() protoreflect.Message {
	mi := &file_chat_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationClosedData.ProtoReflect.Descriptor instead.
func (*ConversationClosedData) Descriptor() ([]byte, []int) {
	return file_chat_events_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationClosedData) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ConversationClosedData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConversationClosedData) GetClosedAt() int64 {
	if x != nil {
		return x.ClosedAt
	}
	return 0
}

var File_chat_events_proto protoreflect.FileDescriptor

const file_chat_events_proto_rawDesc = "" +
	"\n" +
	"\x11chat_events.proto\x12\x16emotion_chat.events.v1\"\x9f\x03\n" +
	"\x11ChatEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12&\n" +
	"\x0ftime_unix_milli\x18\x04 \x01(\x03R\rtimeUnixMilli\x12U\n" +
	"\x0fmessage_created\x18\x05 \x01(\v2*.emotion_chat.events.v1.MessageCreatedDataH\x00R\x0emessageCreated\x12d\n" +
	"\x14conversation_created\x18\x06 \x01(\v2/.emotion_chat.events.v1.ConversationCreatedDataH\x00R\x13conversationCreated\x12a\n" +
	"\x13conversation_closed\x18\a \x01(\v2..emotion_chat.events.v1.ConversationClosedDataH\x00R\x12conversationClosedB\x06\n" +
	"\x04data\"\xc2\x01\n" +
	"\x12MessageCreatedData\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x90\x01\n" +
	"\x17ConversationCreatedData\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"w\n" +
	"\x16ConversationClosedData\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tclosed_at\x18\x03 \x01(\x03R\bclosedAtB/Z-github.com/emotion-echo/shared/pkg/chateventsb\x06proto3"

var (
	file_chat_events_proto_rawDescOnce sync.Once
	file_chat_events_proto_rawDescData []byte
)

func file_chat_events_proto_rawDescGZIP() []byte {
	file_chat_events_proto_rawDescOnce.Do(func() {
		file_chat_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_events_proto_rawDesc), len(file_chat_events_proto_rawDesc)))
	})
	return file_chat_events_proto_rawDescData
}

var file_chat_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chat_events_proto_goTypes = []any{
	(*ChatEventEnvelope)(nil),       // 0: emotion_chat.events.v1.ChatEventEnvelope
	(*MessageCreatedData)(nil),      // 1: emotion_chat.events.v1.MessageCreatedData
	(*ConversationCreatedData)(nil), // 2: emotion_chat.events.v1.ConversationCreatedData
	(*ConversationClosedData)(nil),  // 3: emotion_chat.events.v1.ConversationClosedData
}
var file_chat_events_proto_depIdxs = []int32{
	1, // 0: emotion_chat.events.v1.ChatEventEnvelope.message_created:type_name -> emotion_chat.events.v1.MessageCreatedData
	2, // 1: emotion_chat.events.v1.ChatEventEnvelope.conversation_created:type_name -> emotion_chat.events.v1.ConversationCreatedData
	3, // 2: emotion_chat.events.v1.ChatEventEnvelope.conversation_closed:type_name -> emotion_chat.events.v1.ConversationClosedData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chat_events_proto_init() }
func file_chat_events_proto_init() {
	if File_chat_events_proto != nil {
		return
	}
	file_chat_events_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatEventEnvelope_MessageCreated)(nil),
		(*ChatEventEnvelope_ConversationCreated)(nil),
		(*ChatEventEnvelope_ConversationClosed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_events_proto_rawDesc), len(file_chat_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_events_proto_goTypes,
		DependencyIndexes: file_chat_events_proto_depIdxs,
		MessageInfos:      file_chat_events_proto_msgTypes,
	}.Build()
	File_chat_events_proto = out.File
	file_chat_events_proto_goTypes = nil
	file_chat_events_proto_depIdxs = nil
}
