apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: ee-system
  labels:
    {{- include "apisix-ingress.labels" . | nindent 4 }}
data:
  config.yaml: |
    deployment:
      role: traditional
      role_traditional:
        config_provider: etcd
      etcd:
        host:
          - http://{{ .Values.etcd.host }}.ee-system.svc.cluster.local:{{ .Values.etcd.port }}
        prefix: /apisix
        timeout: 30
    apisix:
      enable_admin: true
      admin_listen:
        port: 9180
      ssl:
        enable: false
    nginx_config:
      error_log_level: warn