// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetMeReq struct {
}

type GetMeResp struct {
	User UserInfo `json:"user"`
}

type GetUserByIdReq struct {
	Id int64 `path:"id"`
}

type GetUserByIdResp struct {
	User UserInfo `json:"user"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Time    int64  `json:"time"`
	Service string `json:"service"`
	Version string `json:"version"`
	DbOK    bool   `json:"dbOk"`
}

type UserInfo struct {
	UserId   int64  `json:"userId"`
	Account  string `json:"account"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
}

// UpdateProfileReq PATCH /api/v1/users/me 的请求体
//
// 所有字段 optional：nil 表示不动；非 nil 表示覆盖/设置
type UpdateProfileReq struct {
	Nickname *string `json:"nickname,optional"`
	Gender   *int16  `json:"gender,optional"`
	Birthday *string `json:"birthday,optional"` // YYYY-MM-DD
	AvatarURL *string `json:"avatarUrl,optional"`
}

// UpdateProfileResp 与 GetMeResp 结构完全一致（用户最新信息）
type UpdateProfileResp = GetMeResp

// LoginReq POST /api/v1/users/login
//
// Stage 33 PR-19a：user-svc 真实登录。前端直接传明文密码（不再 sha256），
// user-svc 用 bcrypt.Verify 与 password_hash 比对。
type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// LoginResp 登录成功响应：返回用户信息（不含密码哈希）
type LoginResp struct {
	User UserInfo `json:"user"`
}

// RegisterReq POST /api/v1/users/register
//
// Stage 33 PR-19a：user-svc 注册。username 唯一；password 明文入库前
// 由 handler 调 password.Hash bcrypt 哈希。
type RegisterReq struct {
	Username         string  `json:"username"`
	Password         string  `json:"password"`
	VerificationCode string  `json:"verificationCode,optional"`
	Phone            *string `json:"phone,optional"`
	Nickname         *string `json:"nickname,optional"`
}

// RegisterResp 注册成功响应
type RegisterResp struct {
	User UserInfo `json:"user"`
}

// AuthErrorResp 鉴权失败响应（统一格式）
type AuthErrorResp struct {
	Error string `json:"error"`
}
