// Stage 36-A2.1 · code generated by hand
//
// 处理 GET /api/v1/conversations（用户隔离的会话列表）
// 关键契约：
//   - 用户必须登录（middleware 已塞 userID）
//   - 仅返回当前 user_id 的会话（不允许跨用户查询）
//   - 按 updated_at desc 排序（最近活跃在前）
//   - hasMore：取 limit+1 行探测，超 limit 则丢弃末位并标 true
package logic

import (
	"context"
	"errors"

	"emotion-echo-chat-svc/internal/middleware"
	"emotion-echo-chat-svc/internal/svc"
	"emotion-echo-chat-svc/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
)

// ListConversationsLogic 处理 GET /api/v1/conversations
type ListConversationsLogic struct {
	logx.Logger
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListConversationsLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListConversationsLogic {
	return &ListConversationsLogic{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

// ListConversations 列出当前用户的会话，按 updated_at desc
func (l *ListConversationsLogic) ListConversations(req *types.ListConversationsReq) (resp *types.ListConversationsResp, err error) {
	uid, ok := l.ctx.Value(middleware.CtxUserIDKey{}).(int64)
	if !ok || uid <= 0 {
		return nil, errors.New("unauthorized: missing user id")
	}

	limit := req.Limit
	if limit <= 0 {
		limit = 20
	}
	offset := req.Offset
	if offset < 0 {
		offset = 0
	}

	// 取 limit+1 探测 hasMore
	convs, err := l.svcCtx.ConversationRepo.ListConversations(l.ctx, uid, limit+1, offset)
	if err != nil {
		return nil, err
	}

	hasMore := len(convs) > limit
	if hasMore {
		convs = convs[:limit]
	}

	out := &types.ListConversationsResp{
		List:    make([]types.ConversationView, 0, len(convs)),
		HasMore: hasMore,
	}
	for _, c := range convs {
		out.List = append(out.List, types.ConversationView{
			Id:        c.ID,
			UserId:    c.UserID,
			Title:     c.Title,
			MsgCount:  c.MessageCount,
			Status:    int(c.Status),
			CreatedAt: c.CreatedAt.UnixMilli(),
			UpdatedAt: c.UpdatedAt.UnixMilli(),
		})
	}
	return out, nil
}
