apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ include "grafana.namespaceObservability" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.adminUser | default "admin" | quote }}
  admin-password: {{ .Values.adminPassword | default "dev-grafana-admin" | quote }}