apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ include "grafana.namespaceObservability" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 3000 }}
      targetPort: http
      protocol: TCP