// proto/user.proto
//
// Stage 62 PR-3.1: user-svc 暴露给 BFF 的 gRPC 接口（gRPC 渐进迁移 Phase 2）
// Sprint E (2026-09-11) 增补: Login / Register RPC
//
// 背景（docs/plans/grpc-inter-service-migration.md §二 决策 A）：
//   Stage 58 PR-GRPC-1~6 已落地 chat-svc → BFF gRPC 化（CHAT_TRANSPORT=grpc 默认）。
//   Sprint E 推广到 user-svc auth：Login / Register 走 gRPC（accessToken 仍由 BFF jwt.Sign 签发）。
//
// 端点 1:1 对齐（emotion-echo-web-bff/internal/downstream/user.go）：
//   GET    /api/v1/users/me       → GetMe
//   PATCH  /api/v1/users/me       → UpdateProfile
//   GET    /api/v1/users/:id      → GetUserById
//   POST   /api/v1/auth/login     → Login       (Sprint E 新增)
//   POST   /api/v1/auth/register  → Register    (Sprint E 新增)
//
// 与 chat.proto 区别：
//   - package: emotion_user.v1（user-svc）
//   - go_package: emotionuser
//   - 仅 unary（user-svc 当前无 stream 需求）
//
// 关联：
//   - docs/plans/stage-62-cleanup-and-grpc-plan.md §二.3 PR-3
//   - emotion-echo-web-bff/internal/downstream/user.go（HTTP 客户端，作为 gRPC fallback）
//   - emotion-echo-user-svc/internal/handler/{user_handler,auth_handler}.go（HTTP handler，将被 gRPC server 复用）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: user.proto

package emotionuser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMeRequest 获取当前用户请求
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

// UpdateProfileRequest 修改用户资料请求
//
// 全 optional 字段（用 wrapper 类型）：nil = 不修改该字段
type UpdateProfileRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Nickname  *string                `protobuf:"bytes,1,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	AvatarUrl *string                `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Gender    *int32                 `protobuf:"varint,3,opt,name=gender,proto3,oneof" json:"gender,omitempty"` // 0=未设置 1=男 2=女
	// E2E-12: 用户个性化配置（fontSize/theme 等），JSON 字符串
	Config        *string `protobuf:"bytes,6,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() int32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UpdateProfileRequest) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

// GetUserByIdRequest 查询用户请求
type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// LoginRequest 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse 登录响应（仅返 user info，accessToken 由 BFF 签发）
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// SecurityQuestion 密保问题（E2E-06，供 D-01=C 找回密码）
type SecurityQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityQuestion) Reset() {
	*x = SecurityQuestion{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityQuestion) ProtoMessage() {}

func (x *SecurityQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityQuestion.ProtoReflect.Descriptor instead.
func (*SecurityQuestion) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *SecurityQuestion) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// verificationCode 可选：dev mode 不强制验证码（生产由 BFF 校验）
	VerificationCode *string `protobuf:"bytes,3,opt,name=verification_code,json=verificationCode,proto3,oneof" json:"verification_code,omitempty"`
	Nickname         *string `protobuf:"bytes,5,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	// E2E-06: 密保问题（必填，1~2 个）
	SecurityQuestions []*SecurityQuestion `protobuf:"bytes,6,rep,name=security_questions,json=securityQuestions,proto3" json:"security_questions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetVerificationCode() string {
	if x != nil && x.VerificationCode != nil {
		return *x.VerificationCode
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetSecurityQuestions() []*SecurityQuestion {
	if x != nil {
		return x.SecurityQuestions
	}
	return nil
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// ResetPasswordRequest 重置密码请求
type ResetPasswordRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	NewPassword      string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ResetPasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResetPasswordRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ResetPasswordResponse 重置密码响应
type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ResetPasswordResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// LogoutRequest 登出请求（空消息体；user_id 从 metadata 取）
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

// LogoutResponse 登出响应
type LogoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success 字段便于 BFF 透传
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// VerifySecurityAnswerRequest 验证密保答案请求（E2E-06，供 D-01=C 找回密码）
type VerifySecurityAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionOrder int32                  `protobuf:"varint,2,opt,name=question_order,json=questionOrder,proto3" json:"question_order,omitempty"` // 1 或 2
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySecurityAnswerRequest) Reset() {
	*x = VerifySecurityAnswerRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySecurityAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySecurityAnswerRequest) ProtoMessage() {}

func (x *VerifySecurityAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySecurityAnswerRequest.ProtoReflect.Descriptor instead.
func (*VerifySecurityAnswerRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *VerifySecurityAnswerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifySecurityAnswerRequest) GetQuestionOrder() int32 {
	if x != nil {
		return x.QuestionOrder
	}
	return 0
}

func (x *VerifySecurityAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// VerifySecurityAnswerResponse 验证密保答案响应
type VerifySecurityAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySecurityAnswerResponse) Reset() {
	*x = VerifySecurityAnswerResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySecurityAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySecurityAnswerResponse) ProtoMessage() {}

func (x *VerifySecurityAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySecurityAnswerResponse.ProtoReflect.Descriptor instead.
func (*VerifySecurityAnswerResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *VerifySecurityAnswerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// VerifySecurityAnswerByUsernameRequest 按用户名验证密保答案请求（R-01 #2）
type VerifySecurityAnswerByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	QuestionOrder int32                  `protobuf:"varint,2,opt,name=question_order,json=questionOrder,proto3" json:"question_order,omitempty"` // 1 或 2
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySecurityAnswerByUsernameRequest) Reset() {
	*x = VerifySecurityAnswerByUsernameRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySecurityAnswerByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySecurityAnswerByUsernameRequest) ProtoMessage() {}

func (x *VerifySecurityAnswerByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySecurityAnswerByUsernameRequest.ProtoReflect.Descriptor instead.
func (*VerifySecurityAnswerByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *VerifySecurityAnswerByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifySecurityAnswerByUsernameRequest) GetQuestionOrder() int32 {
	if x != nil {
		return x.QuestionOrder
	}
	return 0
}

func (x *VerifySecurityAnswerByUsernameRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// VerifySecurityAnswerByUsernameResponse 按用户名验证密保答案响应
//
// 用户不存在与答案错误返回同一种 gRPC 错误（Unauthenticated），
// 防用户名枚举；成功时 success=true。
type VerifySecurityAnswerByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySecurityAnswerByUsernameResponse) Reset() {
	*x = VerifySecurityAnswerByUsernameResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySecurityAnswerByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySecurityAnswerByUsernameResponse) ProtoMessage() {}

func (x *VerifySecurityAnswerByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySecurityAnswerByUsernameResponse.ProtoReflect.Descriptor instead.
func (*VerifySecurityAnswerByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *VerifySecurityAnswerByUsernameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SecurityQuestionInfo 返回给前端的密保问题信息（不含答案）
type SecurityQuestionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionOrder int32                  `protobuf:"varint,1,opt,name=question_order,json=questionOrder,proto3" json:"question_order,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityQuestionInfo) Reset() {
	*x = SecurityQuestionInfo{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityQuestionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityQuestionInfo) ProtoMessage() {}

func (x *SecurityQuestionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityQuestionInfo.ProtoReflect.Descriptor instead.
func (*SecurityQuestionInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *SecurityQuestionInfo) GetQuestionOrder() int32 {
	if x != nil {
		return x.QuestionOrder
	}
	return 0
}

func (x *SecurityQuestionInfo) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

// GetSecurityQuestionsByUsernameRequest 获取密保问题请求
type GetSecurityQuestionsByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityQuestionsByUsernameRequest) Reset() {
	*x = GetSecurityQuestionsByUsernameRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityQuestionsByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityQuestionsByUsernameRequest) ProtoMessage() {}

func (x *GetSecurityQuestionsByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityQuestionsByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetSecurityQuestionsByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetSecurityQuestionsByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// GetSecurityQuestionsByUsernameResponse 获取密保问题响应
type GetSecurityQuestionsByUsernameResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Questions     []*SecurityQuestionInfo `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityQuestionsByUsernameResponse) Reset() {
	*x = GetSecurityQuestionsByUsernameResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityQuestionsByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityQuestionsByUsernameResponse) ProtoMessage() {}

func (x *GetSecurityQuestionsByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityQuestionsByUsernameResponse.ProtoReflect.Descriptor instead.
func (*GetSecurityQuestionsByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetSecurityQuestionsByUsernameResponse) GetQuestions() []*SecurityQuestionInfo {
	if x != nil {
		return x.Questions
	}
	return nil
}

// UserInfo 用户信息视图
//
// 字段命名遵循 emotion_query.proto 已确立的 snake_case
type UserInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username  string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname  string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Gender    int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`                        // 0=未设置 1=男 2=女
	CreatedAt int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	UpdatedAt int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// E2E-12: 用户个性化配置（fontSize/theme 等），JSON 字符串
	Config        *string `protobuf:"bytes,10,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserInfo) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x0femotion_user.v1\"\x0e\n" +
	"\fGetMeRequest\"\xd3\x01\n" +
	"\x14UpdateProfileRequest\x12\x1f\n" +
	"\bnickname\x18\x01 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x03 \x01(\x05H\x02R\x06gender\x88\x01\x01\x12\x1b\n" +
	"\x06config\x18\x06 \x01(\tH\x03R\x06config\x88\x01\x01B\v\n" +
	"\t_nicknameB\r\n" +
	"\v_avatar_urlB\t\n" +
	"\a_genderB\t\n" +
	"\a_configJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\"-\n" +
	"\x12GetUserByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\rLoginResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.emotion_user.v1.UserInfoR\x04user\"F\n" +
	"\x10SecurityQuestion\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"\x97\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x120\n" +
	"\x11verification_code\x18\x03 \x01(\tH\x00R\x10verificationCode\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\x05 \x01(\tH\x01R\bnickname\x88\x01\x01\x12P\n" +
	"\x12security_questions\x18\x06 \x03(\v2!.emotion_user.v1.SecurityQuestionR\x11securityQuestionsB\x14\n" +
	"\x12_verification_codeB\v\n" +
	"\t_nicknameJ\x04\b\x04\x10\x05\"A\n" +
	"\x10RegisterResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.emotion_user.v1.UserInfoR\x04user\"\x82\x01\n" +
	"\x14ResetPasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"F\n" +
	"\x15ResetPasswordResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.emotion_user.v1.UserInfoR\x04user\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"u\n" +
	"\x1bVerifySecurityAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12%\n" +
	"\x0equestion_order\x18\x02 \x01(\x05R\rquestionOrder\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\"8\n" +
	"\x1cVerifySecurityAnswerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x82\x01\n" +
	"%VerifySecurityAnswerByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12%\n" +
	"\x0equestion_order\x18\x02 \x01(\x05R\rquestionOrder\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\"B\n" +
	"&VerifySecurityAnswerByUsernameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x14SecurityQuestionInfo\x12%\n" +
	"\x0equestion_order\x18\x01 \x01(\x05R\rquestionOrder\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"C\n" +
	"%GetSecurityQuestionsByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"m\n" +
	"&GetSecurityQuestionsByUsernameResponse\x12C\n" +
	"\tquestions\x18\x01 \x03(\v2%.emotion_user.v1.SecurityQuestionInfoR\tquestions\"\xfb\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\x06config\x18\n" +
	" \x01(\tH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_configJ\x04\b\x06\x10\aJ\x04\b\a\x10\b2\xd3\a\n" +
	"\vUserService\x12A\n" +
	"\x05GetMe\x12\x1d.emotion_user.v1.GetMeRequest\x1a\x19.emotion_user.v1.UserInfo\x12Q\n" +
	"\rUpdateProfile\x12%.emotion_user.v1.UpdateProfileRequest\x1a\x19.emotion_user.v1.UserInfo\x12M\n" +
	"\vGetUserById\x12#.emotion_user.v1.GetUserByIdRequest\x1a\x19.emotion_user.v1.UserInfo\x12F\n" +
	"\x05Login\x12\x1d.emotion_user.v1.LoginRequest\x1a\x1e.emotion_user.v1.LoginResponse\x12O\n" +
	"\bRegister\x12 .emotion_user.v1.RegisterRequest\x1a!.emotion_user.v1.RegisterResponse\x12^\n" +
	"\rResetPassword\x12%.emotion_user.v1.ResetPasswordRequest\x1a&.emotion_user.v1.ResetPasswordResponse\x12I\n" +
	"\x06Logout\x12\x1e.emotion_user.v1.LogoutRequest\x1a\x1f.emotion_user.v1.LogoutResponse\x12s\n" +
	"\x14VerifySecurityAnswer\x12,.emotion_user.v1.VerifySecurityAnswerRequest\x1a-.emotion_user.v1.VerifySecurityAnswerResponse\x12\x91\x01\n" +
	"\x1eVerifySecurityAnswerByUsername\x126.emotion_user.v1.VerifySecurityAnswerByUsernameRequest\x1a7.emotion_user.v1.VerifySecurityAnswerByUsernameResponse\x12\x91\x01\n" +
	"\x1eGetSecurityQuestionsByUsername\x126.emotion_user.v1.GetSecurityQuestionsByUsernameRequest\x1a7.emotion_user.v1.GetSecurityQuestionsByUsernameResponseB0Z.github.com/emotion-echo/shared/pkg/emotionuserb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_proto_goTypes = []any{
	(*GetMeRequest)(nil),                           // 0: emotion_user.v1.GetMeRequest
	(*UpdateProfileRequest)(nil),                   // 1: emotion_user.v1.UpdateProfileRequest
	(*GetUserByIdRequest)(nil),                     // 2: emotion_user.v1.GetUserByIdRequest
	(*LoginRequest)(nil),                           // 3: emotion_user.v1.LoginRequest
	(*LoginResponse)(nil),                          // 4: emotion_user.v1.LoginResponse
	(*SecurityQuestion)(nil),                       // 5: emotion_user.v1.SecurityQuestion
	(*RegisterRequest)(nil),                        // 6: emotion_user.v1.RegisterRequest
	(*RegisterResponse)(nil),                       // 7: emotion_user.v1.RegisterResponse
	(*ResetPasswordRequest)(nil),                   // 8: emotion_user.v1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),                  // 9: emotion_user.v1.ResetPasswordResponse
	(*LogoutRequest)(nil),                          // 10: emotion_user.v1.LogoutRequest
	(*LogoutResponse)(nil),                         // 11: emotion_user.v1.LogoutResponse
	(*VerifySecurityAnswerRequest)(nil),            // 12: emotion_user.v1.VerifySecurityAnswerRequest
	(*VerifySecurityAnswerResponse)(nil),           // 13: emotion_user.v1.VerifySecurityAnswerResponse
	(*VerifySecurityAnswerByUsernameRequest)(nil),  // 14: emotion_user.v1.VerifySecurityAnswerByUsernameRequest
	(*VerifySecurityAnswerByUsernameResponse)(nil), // 15: emotion_user.v1.VerifySecurityAnswerByUsernameResponse
	(*SecurityQuestionInfo)(nil),                   // 16: emotion_user.v1.SecurityQuestionInfo
	(*GetSecurityQuestionsByUsernameRequest)(nil),  // 17: emotion_user.v1.GetSecurityQuestionsByUsernameRequest
	(*GetSecurityQuestionsByUsernameResponse)(nil), // 18: emotion_user.v1.GetSecurityQuestionsByUsernameResponse
	(*UserInfo)(nil),                               // 19: emotion_user.v1.UserInfo
}
var file_user_proto_depIdxs = []int32{
	19, // 0: emotion_user.v1.LoginResponse.user:type_name -> emotion_user.v1.UserInfo
	5,  // 1: emotion_user.v1.RegisterRequest.security_questions:type_name -> emotion_user.v1.SecurityQuestion
	19, // 2: emotion_user.v1.RegisterResponse.user:type_name -> emotion_user.v1.UserInfo
	19, // 3: emotion_user.v1.ResetPasswordResponse.user:type_name -> emotion_user.v1.UserInfo
	16, // 4: emotion_user.v1.GetSecurityQuestionsByUsernameResponse.questions:type_name -> emotion_user.v1.SecurityQuestionInfo
	0,  // 5: emotion_user.v1.UserService.GetMe:input_type -> emotion_user.v1.GetMeRequest
	1,  // 6: emotion_user.v1.UserService.UpdateProfile:input_type -> emotion_user.v1.UpdateProfileRequest
	2,  // 7: emotion_user.v1.UserService.GetUserById:input_type -> emotion_user.v1.GetUserByIdRequest
	3,  // 8: emotion_user.v1.UserService.Login:input_type -> emotion_user.v1.LoginRequest
	6,  // 9: emotion_user.v1.UserService.Register:input_type -> emotion_user.v1.RegisterRequest
	8,  // 10: emotion_user.v1.UserService.ResetPassword:input_type -> emotion_user.v1.ResetPasswordRequest
	10, // 11: emotion_user.v1.UserService.Logout:input_type -> emotion_user.v1.LogoutRequest
	12, // 12: emotion_user.v1.UserService.VerifySecurityAnswer:input_type -> emotion_user.v1.VerifySecurityAnswerRequest
	14, // 13: emotion_user.v1.UserService.VerifySecurityAnswerByUsername:input_type -> emotion_user.v1.VerifySecurityAnswerByUsernameRequest
	17, // 14: emotion_user.v1.UserService.GetSecurityQuestionsByUsername:input_type -> emotion_user.v1.GetSecurityQuestionsByUsernameRequest
	19, // 15: emotion_user.v1.UserService.GetMe:output_type -> emotion_user.v1.UserInfo
	19, // 16: emotion_user.v1.UserService.UpdateProfile:output_type -> emotion_user.v1.UserInfo
	19, // 17: emotion_user.v1.UserService.GetUserById:output_type -> emotion_user.v1.UserInfo
	4,  // 18: emotion_user.v1.UserService.Login:output_type -> emotion_user.v1.LoginResponse
	7,  // 19: emotion_user.v1.UserService.Register:output_type -> emotion_user.v1.RegisterResponse
	9,  // 20: emotion_user.v1.UserService.ResetPassword:output_type -> emotion_user.v1.ResetPasswordResponse
	11, // 21: emotion_user.v1.UserService.Logout:output_type -> emotion_user.v1.LogoutResponse
	13, // 22: emotion_user.v1.UserService.VerifySecurityAnswer:output_type -> emotion_user.v1.VerifySecurityAnswerResponse
	15, // 23: emotion_user.v1.UserService.VerifySecurityAnswerByUsername:output_type -> emotion_user.v1.VerifySecurityAnswerByUsernameResponse
	18, // 24: emotion_user.v1.UserService.GetSecurityQuestionsByUsername:output_type -> emotion_user.v1.GetSecurityQuestionsByUsernameResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_proto_msgTypes[6].OneofWrappers = []any{}
	file_user_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
