// proto/user.proto
//
// Stage 62 PR-3.1: user-svc 暴露给 BFF 的 gRPC 接口（gRPC 渐进迁移 Phase 2）
// Sprint E (2026-09-11) 增补: Login / Register RPC
//
// 背景（docs/plans/grpc-inter-service-migration.md §二 决策 A）：
//   Stage 58 PR-GRPC-1~6 已落地 chat-svc → BFF gRPC 化（CHAT_TRANSPORT=grpc 默认）。
//   Sprint E 推广到 user-svc auth：Login / Register 走 gRPC（accessToken 仍由 BFF jwt.Sign 签发）。
//
// 端点 1:1 对齐（emotion-echo-web-bff/internal/downstream/user.go）：
//   GET    /api/v1/users/me       → GetMe
//   PATCH  /api/v1/users/me       → UpdateProfile
//   GET    /api/v1/users/:id      → GetUserById
//   POST   /api/v1/auth/login     → Login       (Sprint E 新增)
//   POST   /api/v1/auth/register  → Register    (Sprint E 新增)
//
// 与 chat.proto 区别：
//   - package: emotion_user.v1（user-svc）
//   - go_package: emotionuser
//   - 仅 unary（user-svc 当前无 stream 需求）
//
// 关联：
//   - docs/plans/stage-62-cleanup-and-grpc-plan.md §二.3 PR-3
//   - emotion-echo-web-bff/internal/downstream/user.go（HTTP 客户端，作为 gRPC fallback）
//   - emotion-echo-user-svc/internal/handler/{user_handler,auth_handler}.go（HTTP handler，将被 gRPC server 复用）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: user.proto

package emotionuser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetMe_FullMethodName         = "/emotion_user.v1.UserService/GetMe"
	UserService_UpdateProfile_FullMethodName = "/emotion_user.v1.UserService/UpdateProfile"
	UserService_GetUserById_FullMethodName   = "/emotion_user.v1.UserService/GetUserById"
	UserService_Login_FullMethodName         = "/emotion_user.v1.UserService/Login"
	UserService_Register_FullMethodName      = "/emotion_user.v1.UserService/Register"
	UserService_ResetPassword_FullMethodName = "/emotion_user.v1.UserService/ResetPassword"
	UserService_Logout_FullMethodName        = "/emotion_user.v1.UserService/Logout"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # UserService user-svc 暴露给 BFF 的接口
//
// user-svc 同时跑 HTTP (:8888) + gRPC (:8887)。前端继续走 HTTP（APISIX 网关），
// 内部 BFF 走 gRPC。
type UserServiceClient interface {
	// GetMe 获取当前用户信息
	//
	// 鉴权：user_id 通过 metadata "x-user-id" 传（与 emotion_query.proto / emotion_chat.proto 一致）
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserInfo, error)
	// UpdateProfile 修改当前用户资料
	//
	// 全 optional 指针：nil = 不修改（与 HTTP PATCH 语义一致）
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserInfo, error)
	// GetUserById 根据 user_id 查询用户（公开信息）
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error)
	// Login 用 username + password 登录，返 UserInfo
	//
	// 注意：accessToken 不在此 RPC 返回——由 BFF 收到 UserInfo 后用 jwt.Manager 自行签发。
	// 这样 gRPC 契约只关心业务语义（用户身份），鉴权令牌签发仍归 BFF 单点管控。
	//
	// 鉴权：匿名调用（无 metadata x-user-id）。userid 拦截器需在 server 端跳过此 RPC。
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Register 新建用户（username 唯一），返 UserInfo
	//
	// 鉴权：匿名调用（同 Login）。
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// ResetPassword 用 username + verificationCode + newPassword 重置密码，返 UserInfo
	//
	// 鉴权：匿名调用（同 Login/Register）。userid 拦截器跳过。
	// 当前 Sprint 1 PR-4c-4 后的行为：verificationCode 由 BFF 校验后转发 user-svc，
	// 这里是 dev mode（user-svc 自己校验 verificationCode 字段）；prod 接入 SMS/Email 后由 BFF 校验。
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	// Logout 登出（服务端无状态，主要让客户端清 token；这里返 OK 即可）
	//
	// 鉴权：需要 metadata x-user-id（userid 拦截器不跳过此 RPC）。
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserService_GetUserById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, UserService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, UserService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, UserService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// # UserService user-svc 暴露给 BFF 的接口
//
// user-svc 同时跑 HTTP (:8888) + gRPC (:8887)。前端继续走 HTTP（APISIX 网关），
// 内部 BFF 走 gRPC。
type UserServiceServer interface {
	// GetMe 获取当前用户信息
	//
	// 鉴权：user_id 通过 metadata "x-user-id" 传（与 emotion_query.proto / emotion_chat.proto 一致）
	GetMe(context.Context, *GetMeRequest) (*UserInfo, error)
	// UpdateProfile 修改当前用户资料
	//
	// 全 optional 指针：nil = 不修改（与 HTTP PATCH 语义一致）
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UserInfo, error)
	// GetUserById 根据 user_id 查询用户（公开信息）
	GetUserById(context.Context, *GetUserByIdRequest) (*UserInfo, error)
	// Login 用 username + password 登录，返 UserInfo
	//
	// 注意：accessToken 不在此 RPC 返回——由 BFF 收到 UserInfo 后用 jwt.Manager 自行签发。
	// 这样 gRPC 契约只关心业务语义（用户身份），鉴权令牌签发仍归 BFF 单点管控。
	//
	// 鉴权：匿名调用（无 metadata x-user-id）。userid 拦截器需在 server 端跳过此 RPC。
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Register 新建用户（username 唯一），返 UserInfo
	//
	// 鉴权：匿名调用（同 Login）。
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// ResetPassword 用 username + verificationCode + newPassword 重置密码，返 UserInfo
	//
	// 鉴权：匿名调用（同 Login/Register）。userid 拦截器跳过。
	// 当前 Sprint 1 PR-4c-4 后的行为：verificationCode 由 BFF 校验后转发 user-svc，
	// 这里是 dev mode（user-svc 自己校验 verificationCode 字段）；prod 接入 SMS/Email 后由 BFF 校验。
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	// Logout 登出（服务端无状态，主要让客户端清 token；这里返 OK 即可）
	//
	// 鉴权：需要 metadata x-user-id（userid 拦截器不跳过此 RPC）。
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetMe(context.Context, *GetMeRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) GetUserById(context.Context, *GetUserByIdRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserById not implemented")
}
func (UnimplementedUserServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedUserServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _UserService_GetMe_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _UserService_GetUserById_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
