// proto/user.proto
//
// Stage 62 PR-3.1: user-svc 暴露给 BFF 的 gRPC 接口（gRPC 渐进迁移 Phase 2）
//
// 背景（docs/plans/grpc-inter-service-migration.md §二 决策 A）：
//   Stage 58 PR-GRPC-1~6 已落地 chat-svc → BFF gRPC 化（CHAT_TRANSPORT=grpc 默认）。
//   本批把同模式推广到 user-svc：HTTP :8888 保留给前端（APISIX 网关），
//   内部 BFF 走 gRPC :8887（feature flag: USER_TRANSPORT=grpc|http）。
//
// 端点 1:1 对齐（emotion-echo-web-bff/internal/downstream/user.go）：
//   GET    /api/v1/users/me       → GetMe
//   PATCH  /api/v1/users/me       → UpdateProfile
//   GET    /api/v1/users/:id      → GetUserById
//
// 与 chat.proto 区别：
//   - package: emotion_user.v1（user-svc）
//   - go_package: emotionuser
//   - 仅 unary（user-svc 当前无 stream 需求）
//
// 关联：
//   - docs/plans/stage-62-cleanup-and-grpc-plan.md §二.3 PR-3
//   - emotion-echo-web-bff/internal/downstream/user.go（HTTP 客户端，作为 gRPC fallback）
//   - emotion-echo-user-svc/internal/handler/{user_handler,auth_handler}.go（HTTP handler，将被 gRPC server 复用）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: user.proto

package emotionuser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetMe_FullMethodName         = "/emotion_user.v1.UserService/GetMe"
	UserService_UpdateProfile_FullMethodName = "/emotion_user.v1.UserService/UpdateProfile"
	UserService_GetUserById_FullMethodName   = "/emotion_user.v1.UserService/GetUserById"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # UserService user-svc 暴露给 BFF 的接口
//
// user-svc 同时跑 HTTP (:8888) + gRPC (:8887)。前端继续走 HTTP（APISIX 网关），
// 内部 BFF 走 gRPC（本批 PR-3.1~3.4 推进）。
type UserServiceClient interface {
	// GetMe 获取当前用户信息
	//
	// 鉴权：user_id 通过 metadata "x-user-id" 传（与 emotion_query.proto / emotion_chat.proto 一致）
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserInfo, error)
	// UpdateProfile 修改当前用户资料
	//
	// 全 optional 指针：nil = 不修改（与 HTTP PATCH 语义一致）
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserInfo, error)
	// GetUserById 根据 user_id 查询用户（公开信息）
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserService_GetUserById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// # UserService user-svc 暴露给 BFF 的接口
//
// user-svc 同时跑 HTTP (:8888) + gRPC (:8887)。前端继续走 HTTP（APISIX 网关），
// 内部 BFF 走 gRPC（本批 PR-3.1~3.4 推进）。
type UserServiceServer interface {
	// GetMe 获取当前用户信息
	//
	// 鉴权：user_id 通过 metadata "x-user-id" 传（与 emotion_query.proto / emotion_chat.proto 一致）
	GetMe(context.Context, *GetMeRequest) (*UserInfo, error)
	// UpdateProfile 修改当前用户资料
	//
	// 全 optional 指针：nil = 不修改（与 HTTP PATCH 语义一致）
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UserInfo, error)
	// GetUserById 根据 user_id 查询用户（公开信息）
	GetUserById(context.Context, *GetUserByIdRequest) (*UserInfo, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetMe(context.Context, *GetMeRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) GetUserById(context.Context, *GetUserByIdRequest) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserById not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _UserService_GetMe_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _UserService_GetUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
