// Package types — reports.go
//
// Stage 30-A reports endpoint response/request types. Co-located
// with goctl-generated types.go (which we don't modify per
// "Code generated by goctl. DO NOT EDIT." marker + AGENTS §四).
//
// Why a separate file instead of editing types.go:
//   - types.go is regenerated by goctl on next code-gen pass.
//   - Hand-written additions live here, isolated, so goctl's
//     future regen won't clobber them.
package types

import (
	"emotion-echo-analytics-svc/internal/repository"
)

// Re-export so handler / logic 层的 import 路径短。
type (
	DailyReport  = repository.DailyReport
	TrendReport  = repository.TrendReport
	TrendPoint   = repository.TrendPoint
)

// GetDailyReportReq GET /api/v1/reports/daily
type GetDailyReportReq struct {
	UserID int64  `json:"userId"`
	Date   string `json:"date"` // YYYY-MM-DD（空则今天）
}

// GetDailyReportResp
type GetDailyReportResp struct {
	Report *DailyReport `json:"report"`
}

// GetTrendReportReq GET /api/v1/reports/trend
type GetTrendReportReq struct {
	UserID    int64  `json:"userId"`
	Type      string `json:"type"` // weekly | monthly | yearly
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

// GetTrendReportResp
type GetTrendReportResp struct {
	Report *TrendReport `json:"report"`
}