// proto/metric.proto
//
// Stage 62 PR-3.1: analytics-svc 暴露给 BFF 的 gRPC 接口（gRPC 渐进迁移 Phase 2）
//
// 背景（docs/plans/grpc-inter-service-migration.md §二 决策 A）：
//   analytics-svc HTTP :8893 保留给前端，内部 BFF 走 gRPC :8885
//   （feature flag: ANALYTICS_TRANSPORT=grpc|http）。
//
// 端点 1:1 对齐（emotion-echo-web-bff/internal/downstream/analytics.go）：
//   GET    /api/v1/reports/daily                      → ReportsDaily
//   GET    /api/v1/reports/trend                      → ReportsTrend
//   GET    /api/v1/user-behavior/day-night            → UserBehaviorDayNight
//   GET    /api/v1/user-behavior/depth                → UserBehaviorDepth
//   GET    /api/v1/user-behavior/frequency            → UserBehaviorFrequency
//   GET    /api/v1/mental-health/assessment           → MentalHealthAssessment
//   GET    /api/v1/mental-health/history                 → MentalHealthHistory
//   POST   /api/v1/mental-health/trigger              → MentalHealthTrigger
//   GET    /api/v1/mental-health/trend                → MentalHealthTrend
//
// 与 chat.proto / user.proto / agent.proto 区别：
//   - package: emotion_analytics.v1
//   - go_package: emotionanalytics
//   - 9 个 RPC（最大单一服务）
//
// 命名说明：
//   proto 文件名用 `metric.proto`（与 agent.proto 同理：避免与未来 `_service.proto`
//   命名冲突；go_package 保留 emotionanalytics 语义）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: metric.proto

package emotionanalytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DateRange 公共日期范围
type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     int64                  `protobuf:"varint,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // unix seconds (start of day)
	EndDate       int64                  `protobuf:"varint,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // unix seconds (end of day, inclusive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{0}
}

func (x *DateRange) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *DateRange) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

// ChartDataPoint 图表数据点
type ChartDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // x 轴（unix seconds）
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`        // y 轴
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`          // 显示标签（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartDataPoint) Reset() {
	*x = ChartDataPoint{}
	mi := &file_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartDataPoint) ProtoMessage() {}

func (x *ChartDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartDataPoint.ProtoReflect.Descriptor instead.
func (*ChartDataPoint) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{1}
}

func (x *ChartDataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChartDataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ChartDataPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// EmotionDistribution 情绪分布
type EmotionDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotion       string                 `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"` // "happy" / "sad" / "angry" / "neutral" / ...
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionDistribution) Reset() {
	*x = EmotionDistribution{}
	mi := &file_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionDistribution) ProtoMessage() {}

func (x *EmotionDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionDistribution.ProtoReflect.Descriptor instead.
func (*EmotionDistribution) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{2}
}

func (x *EmotionDistribution) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *EmotionDistribution) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EmotionDistribution) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// UserBehaviorRequest 用户行为请求基类（公共参数）
type UserBehaviorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DateRange     *DateRange             `protobuf:"bytes,2,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBehaviorRequest) Reset() {
	*x = UserBehaviorRequest{}
	mi := &file_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBehaviorRequest) ProtoMessage() {}

func (x *UserBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBehaviorRequest.ProtoReflect.Descriptor instead.
func (*UserBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{3}
}

func (x *UserBehaviorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBehaviorRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

// ReportsDailyRequest 日报请求
type ReportsDailyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          int64                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"` // unix seconds (start of day, 0=今天)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportsDailyRequest) Reset() {
	*x = ReportsDailyRequest{}
	mi := &file_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportsDailyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportsDailyRequest) ProtoMessage() {}

func (x *ReportsDailyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportsDailyRequest.ProtoReflect.Descriptor instead.
func (*ReportsDailyRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{4}
}

func (x *ReportsDailyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportsDailyRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

// ReportsDailyResponse 日报响应
type ReportsDailyResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Summary             string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"` // 自然语言总结
	EmotionDistribution []*EmotionDistribution `protobuf:"bytes,2,rep,name=emotion_distribution,json=emotionDistribution,proto3" json:"emotion_distribution,omitempty"`
	EmotionTrend        []*ChartDataPoint      `protobuf:"bytes,3,rep,name=emotion_trend,json=emotionTrend,proto3" json:"emotion_trend,omitempty"`
	MessageCount        int32                  `protobuf:"varint,4,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	ConversationCount   int32                  `protobuf:"varint,5,opt,name=conversation_count,json=conversationCount,proto3" json:"conversation_count,omitempty"`
	Date                int64                  `protobuf:"varint,6,opt,name=date,proto3" json:"date,omitempty"` // echo back
	// Stage 82 PR-3b：6 类消息意图分布（intent=” 的历史行不计入）
	IntentDistribution []*IntentCount `protobuf:"bytes,7,rep,name=intent_distribution,json=intentDistribution,proto3" json:"intent_distribution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReportsDailyResponse) Reset() {
	*x = ReportsDailyResponse{}
	mi := &file_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportsDailyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportsDailyResponse) ProtoMessage() {}

func (x *ReportsDailyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportsDailyResponse.ProtoReflect.Descriptor instead.
func (*ReportsDailyResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{5}
}

func (x *ReportsDailyResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReportsDailyResponse) GetEmotionDistribution() []*EmotionDistribution {
	if x != nil {
		return x.EmotionDistribution
	}
	return nil
}

func (x *ReportsDailyResponse) GetEmotionTrend() []*ChartDataPoint {
	if x != nil {
		return x.EmotionTrend
	}
	return nil
}

func (x *ReportsDailyResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *ReportsDailyResponse) GetConversationCount() int32 {
	if x != nil {
		return x.ConversationCount
	}
	return 0
}

func (x *ReportsDailyResponse) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ReportsDailyResponse) GetIntentDistribution() []*IntentCount {
	if x != nil {
		return x.IntentDistribution
	}
	return nil
}

// IntentCount 单类意图计数（PR-3b）
type IntentCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        string                 `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"` // emotional_support/study_help/tech_help/career_help/lifestyle/other
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentCount) Reset() {
	*x = IntentCount{}
	mi := &file_metric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentCount) ProtoMessage() {}

func (x *IntentCount) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentCount.ProtoReflect.Descriptor instead.
func (*IntentCount) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{6}
}

func (x *IntentCount) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *IntentCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ReportsTrendRequest 趋势请求
type ReportsTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "daily" / "weekly" / "monthly"
	DateRange     *DateRange             `protobuf:"bytes,3,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportsTrendRequest) Reset() {
	*x = ReportsTrendRequest{}
	mi := &file_metric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportsTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportsTrendRequest) ProtoMessage() {}

func (x *ReportsTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportsTrendRequest.ProtoReflect.Descriptor instead.
func (*ReportsTrendRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{7}
}

func (x *ReportsTrendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportsTrendRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReportsTrendRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

// ReportsTrendResponse 趋势响应
type ReportsTrendResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DataPoints []*ChartDataPoint      `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Type       string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // echo back
	// Stage 85：区间意图分布（msg_summary_v.intent 聚合，” 未分类不计入；
	// 服务端按 6 类白名单确定性顺序输出）
	IntentDistribution []*IntentCount `protobuf:"bytes,3,rep,name=intent_distribution,json=intentDistribution,proto3" json:"intent_distribution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReportsTrendResponse) Reset() {
	*x = ReportsTrendResponse{}
	mi := &file_metric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportsTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportsTrendResponse) ProtoMessage() {}

func (x *ReportsTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportsTrendResponse.ProtoReflect.Descriptor instead.
func (*ReportsTrendResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{8}
}

func (x *ReportsTrendResponse) GetDataPoints() []*ChartDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *ReportsTrendResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReportsTrendResponse) GetIntentDistribution() []*IntentCount {
	if x != nil {
		return x.IntentDistribution
	}
	return nil
}

// UserBehaviorDayNightResponse 昼夜分布响应
type UserBehaviorDayNightResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 24 小时 × 2 类别（active / message）
	ActiveHours   []*ChartDataPoint `protobuf:"bytes,1,rep,name=active_hours,json=activeHours,proto3" json:"active_hours,omitempty"`
	MessageHours  []*ChartDataPoint `protobuf:"bytes,2,rep,name=message_hours,json=messageHours,proto3" json:"message_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBehaviorDayNightResponse) Reset() {
	*x = UserBehaviorDayNightResponse{}
	mi := &file_metric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBehaviorDayNightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBehaviorDayNightResponse) ProtoMessage() {}

func (x *UserBehaviorDayNightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBehaviorDayNightResponse.ProtoReflect.Descriptor instead.
func (*UserBehaviorDayNightResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{9}
}

func (x *UserBehaviorDayNightResponse) GetActiveHours() []*ChartDataPoint {
	if x != nil {
		return x.ActiveHours
	}
	return nil
}

func (x *UserBehaviorDayNightResponse) GetMessageHours() []*ChartDataPoint {
	if x != nil {
		return x.MessageHours
	}
	return nil
}

// UserBehaviorDepthResponse 深度响应（会话长度分布）
type UserBehaviorDepthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话长度分桶（短/中/长）
	Buckets       []*ChartDataPoint `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	AverageLength float64           `protobuf:"fixed64,2,opt,name=average_length,json=averageLength,proto3" json:"average_length,omitempty"` // 平均会话长度（消息数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBehaviorDepthResponse) Reset() {
	*x = UserBehaviorDepthResponse{}
	mi := &file_metric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBehaviorDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBehaviorDepthResponse) ProtoMessage() {}

func (x *UserBehaviorDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBehaviorDepthResponse.ProtoReflect.Descriptor instead.
func (*UserBehaviorDepthResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{10}
}

func (x *UserBehaviorDepthResponse) GetBuckets() []*ChartDataPoint {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *UserBehaviorDepthResponse) GetAverageLength() float64 {
	if x != nil {
		return x.AverageLength
	}
	return 0
}

// UserBehaviorFrequencyResponse 频率响应
type UserBehaviorFrequencyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// daily_active: [{date, active}]
	DailyActive   []*ChartDataPoint `protobuf:"bytes,1,rep,name=daily_active,json=dailyActive,proto3" json:"daily_active,omitempty"`
	StreakDays    float64           `protobuf:"fixed64,2,opt,name=streak_days,json=streakDays,proto3" json:"streak_days,omitempty"` // 连续活跃天数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBehaviorFrequencyResponse) Reset() {
	*x = UserBehaviorFrequencyResponse{}
	mi := &file_metric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBehaviorFrequencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBehaviorFrequencyResponse) ProtoMessage() {}

func (x *UserBehaviorFrequencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBehaviorFrequencyResponse.ProtoReflect.Descriptor instead.
func (*UserBehaviorFrequencyResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{11}
}

func (x *UserBehaviorFrequencyResponse) GetDailyActive() []*ChartDataPoint {
	if x != nil {
		return x.DailyActive
	}
	return nil
}

func (x *UserBehaviorFrequencyResponse) GetStreakDays() float64 {
	if x != nil {
		return x.StreakDays
	}
	return 0
}

// MentalHealthAssessmentRequest 综合评估请求
type MentalHealthAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          int64                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthAssessmentRequest) Reset() {
	*x = MentalHealthAssessmentRequest{}
	mi := &file_metric_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthAssessmentRequest) ProtoMessage() {}

func (x *MentalHealthAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthAssessmentRequest.ProtoReflect.Descriptor instead.
func (*MentalHealthAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{12}
}

func (x *MentalHealthAssessmentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MentalHealthAssessmentRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

// MentalHealthAssessmentResponse 综合评估响应
type MentalHealthAssessmentResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Summary             string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Score               float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                        // 综合评分（0-100）
	RiskLevel           string                 `protobuf:"bytes,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"` // "low" / "moderate" / "high" / "severe"
	EmotionDistribution []*EmotionDistribution `protobuf:"bytes,4,rep,name=emotion_distribution,json=emotionDistribution,proto3" json:"emotion_distribution,omitempty"`
	TriggeredAlertCount int32                  `protobuf:"varint,5,opt,name=triggered_alert_count,json=triggeredAlertCount,proto3" json:"triggered_alert_count,omitempty"` // 触发的告警数
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MentalHealthAssessmentResponse) Reset() {
	*x = MentalHealthAssessmentResponse{}
	mi := &file_metric_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthAssessmentResponse) ProtoMessage() {}

func (x *MentalHealthAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthAssessmentResponse.ProtoReflect.Descriptor instead.
func (*MentalHealthAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{13}
}

func (x *MentalHealthAssessmentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MentalHealthAssessmentResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MentalHealthAssessmentResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *MentalHealthAssessmentResponse) GetEmotionDistribution() []*EmotionDistribution {
	if x != nil {
		return x.EmotionDistribution
	}
	return nil
}

func (x *MentalHealthAssessmentResponse) GetTriggeredAlertCount() int32 {
	if x != nil {
		return x.TriggeredAlertCount
	}
	return 0
}

// MentalHealthHistoryRequest 历史请求
type MentalHealthHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DateRange     *DateRange             `protobuf:"bytes,2,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthHistoryRequest) Reset() {
	*x = MentalHealthHistoryRequest{}
	mi := &file_metric_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthHistoryRequest) ProtoMessage() {}

func (x *MentalHealthHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthHistoryRequest.ProtoReflect.Descriptor instead.
func (*MentalHealthHistoryRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{14}
}

func (x *MentalHealthHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MentalHealthHistoryRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

// MentalHealthHistoryResponse 历史响应
type MentalHealthHistoryResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Records       []*MentalHealthAssessmentResponse `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthHistoryResponse) Reset() {
	*x = MentalHealthHistoryResponse{}
	mi := &file_metric_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthHistoryResponse) ProtoMessage() {}

func (x *MentalHealthHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthHistoryResponse.ProtoReflect.Descriptor instead.
func (*MentalHealthHistoryResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{15}
}

func (x *MentalHealthHistoryResponse) GetRecords() []*MentalHealthAssessmentResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

// MentalHealthTriggerRequest 触发请求
type MentalHealthTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TriggerReason string                 `protobuf:"bytes,2,opt,name=trigger_reason,json=triggerReason,proto3" json:"trigger_reason,omitempty"` // "manual" / "scheduled" / "auto"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthTriggerRequest) Reset() {
	*x = MentalHealthTriggerRequest{}
	mi := &file_metric_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthTriggerRequest) ProtoMessage() {}

func (x *MentalHealthTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthTriggerRequest.ProtoReflect.Descriptor instead.
func (*MentalHealthTriggerRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{16}
}

func (x *MentalHealthTriggerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MentalHealthTriggerRequest) GetTriggerReason() string {
	if x != nil {
		return x.TriggerReason
	}
	return ""
}

// MentalHealthTriggerResponse 触发响应
type MentalHealthTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggered     bool                   `protobuf:"varint,1,opt,name=triggered,proto3" json:"triggered,omitempty"`
	AssessmentId  int64                  `protobuf:"varint,2,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"` // 新建评估 ID（0 = 未新建）
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthTriggerResponse) Reset() {
	*x = MentalHealthTriggerResponse{}
	mi := &file_metric_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthTriggerResponse) ProtoMessage() {}

func (x *MentalHealthTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthTriggerResponse.ProtoReflect.Descriptor instead.
func (*MentalHealthTriggerResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{17}
}

func (x *MentalHealthTriggerResponse) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

func (x *MentalHealthTriggerResponse) GetAssessmentId() int64 {
	if x != nil {
		return x.AssessmentId
	}
	return 0
}

func (x *MentalHealthTriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MentalHealthTrendRequest 趋势请求
type MentalHealthTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DateRange     *DateRange             `protobuf:"bytes,2,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthTrendRequest) Reset() {
	*x = MentalHealthTrendRequest{}
	mi := &file_metric_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthTrendRequest) ProtoMessage() {}

func (x *MentalHealthTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthTrendRequest.ProtoReflect.Descriptor instead.
func (*MentalHealthTrendRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{18}
}

func (x *MentalHealthTrendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MentalHealthTrendRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

// MentalHealthTrendResponse 趋势响应
type MentalHealthTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScoreTrend    []*ChartDataPoint      `protobuf:"bytes,1,rep,name=score_trend,json=scoreTrend,proto3" json:"score_trend,omitempty"` // 综合评分趋势
	RiskTrend     []*ChartDataPoint      `protobuf:"bytes,2,rep,name=risk_trend,json=riskTrend,proto3" json:"risk_trend,omitempty"`    // 风险等级趋势
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentalHealthTrendResponse) Reset() {
	*x = MentalHealthTrendResponse{}
	mi := &file_metric_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentalHealthTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentalHealthTrendResponse) ProtoMessage() {}

func (x *MentalHealthTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentalHealthTrendResponse.ProtoReflect.Descriptor instead.
func (*MentalHealthTrendResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{19}
}

func (x *MentalHealthTrendResponse) GetScoreTrend() []*ChartDataPoint {
	if x != nil {
		return x.ScoreTrend
	}
	return nil
}

func (x *MentalHealthTrendResponse) GetRiskTrend() []*ChartDataPoint {
	if x != nil {
		return x.RiskTrend
	}
	return nil
}

var File_metric_proto protoreflect.FileDescriptor

const file_metric_proto_rawDesc = "" +
	"\n" +
	"\fmetric.proto\x12\x14emotion_analytics.v1\"E\n" +
	"\tDateRange\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\x03R\aendDate\"Z\n" +
	"\x0eChartDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"e\n" +
	"\x13EmotionDistribution\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"n\n" +
	"\x13UserBehaviorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12>\n" +
	"\n" +
	"date_range\x18\x02 \x01(\v2\x1f.emotion_analytics.v1.DateRangeR\tdateRange\"B\n" +
	"\x13ReportsDailyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\"\x95\x03\n" +
	"\x14ReportsDailyResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\\\n" +
	"\x14emotion_distribution\x18\x02 \x03(\v2).emotion_analytics.v1.EmotionDistributionR\x13emotionDistribution\x12I\n" +
	"\remotion_trend\x18\x03 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\femotionTrend\x12#\n" +
	"\rmessage_count\x18\x04 \x01(\x05R\fmessageCount\x12-\n" +
	"\x12conversation_count\x18\x05 \x01(\x05R\x11conversationCount\x12\x12\n" +
	"\x04date\x18\x06 \x01(\x03R\x04date\x12R\n" +
	"\x13intent_distribution\x18\a \x03(\v2!.emotion_analytics.v1.IntentCountR\x12intentDistribution\";\n" +
	"\vIntentCount\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x82\x01\n" +
	"\x13ReportsTrendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12>\n" +
	"\n" +
	"date_range\x18\x03 \x01(\v2\x1f.emotion_analytics.v1.DateRangeR\tdateRange\"\xc5\x01\n" +
	"\x14ReportsTrendResponse\x12E\n" +
	"\vdata_points\x18\x01 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\n" +
	"dataPoints\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12R\n" +
	"\x13intent_distribution\x18\x03 \x03(\v2!.emotion_analytics.v1.IntentCountR\x12intentDistribution\"\xb2\x01\n" +
	"\x1cUserBehaviorDayNightResponse\x12G\n" +
	"\factive_hours\x18\x01 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\vactiveHours\x12I\n" +
	"\rmessage_hours\x18\x02 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\fmessageHours\"\x82\x01\n" +
	"\x19UserBehaviorDepthResponse\x12>\n" +
	"\abuckets\x18\x01 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\abuckets\x12%\n" +
	"\x0eaverage_length\x18\x02 \x01(\x01R\raverageLength\"\x89\x01\n" +
	"\x1dUserBehaviorFrequencyResponse\x12G\n" +
	"\fdaily_active\x18\x01 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\vdailyActive\x12\x1f\n" +
	"\vstreak_days\x18\x02 \x01(\x01R\n" +
	"streakDays\"L\n" +
	"\x1dMentalHealthAssessmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\"\x81\x02\n" +
	"\x1eMentalHealthAssessmentResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\tR\triskLevel\x12\\\n" +
	"\x14emotion_distribution\x18\x04 \x03(\v2).emotion_analytics.v1.EmotionDistributionR\x13emotionDistribution\x122\n" +
	"\x15triggered_alert_count\x18\x05 \x01(\x05R\x13triggeredAlertCount\"u\n" +
	"\x1aMentalHealthHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12>\n" +
	"\n" +
	"date_range\x18\x02 \x01(\v2\x1f.emotion_analytics.v1.DateRangeR\tdateRange\"m\n" +
	"\x1bMentalHealthHistoryResponse\x12N\n" +
	"\arecords\x18\x01 \x03(\v24.emotion_analytics.v1.MentalHealthAssessmentResponseR\arecords\"\\\n" +
	"\x1aMentalHealthTriggerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12%\n" +
	"\x0etrigger_reason\x18\x02 \x01(\tR\rtriggerReason\"z\n" +
	"\x1bMentalHealthTriggerResponse\x12\x1c\n" +
	"\ttriggered\x18\x01 \x01(\bR\ttriggered\x12#\n" +
	"\rassessment_id\x18\x02 \x01(\x03R\fassessmentId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"s\n" +
	"\x18MentalHealthTrendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12>\n" +
	"\n" +
	"date_range\x18\x02 \x01(\v2\x1f.emotion_analytics.v1.DateRangeR\tdateRange\"\xa7\x01\n" +
	"\x19MentalHealthTrendResponse\x12E\n" +
	"\vscore_trend\x18\x01 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\n" +
	"scoreTrend\x12C\n" +
	"\n" +
	"risk_trend\x18\x02 \x03(\v2$.emotion_analytics.v1.ChartDataPointR\triskTrend2\xb5\b\n" +
	"\x10AnalyticsService\x12e\n" +
	"\fReportsDaily\x12).emotion_analytics.v1.ReportsDailyRequest\x1a*.emotion_analytics.v1.ReportsDailyResponse\x12e\n" +
	"\fReportsTrend\x12).emotion_analytics.v1.ReportsTrendRequest\x1a*.emotion_analytics.v1.ReportsTrendResponse\x12u\n" +
	"\x14UserBehaviorDayNight\x12).emotion_analytics.v1.UserBehaviorRequest\x1a2.emotion_analytics.v1.UserBehaviorDayNightResponse\x12o\n" +
	"\x11UserBehaviorDepth\x12).emotion_analytics.v1.UserBehaviorRequest\x1a/.emotion_analytics.v1.UserBehaviorDepthResponse\x12w\n" +
	"\x15UserBehaviorFrequency\x12).emotion_analytics.v1.UserBehaviorRequest\x1a3.emotion_analytics.v1.UserBehaviorFrequencyResponse\x12\x83\x01\n" +
	"\x16MentalHealthAssessment\x123.emotion_analytics.v1.MentalHealthAssessmentRequest\x1a4.emotion_analytics.v1.MentalHealthAssessmentResponse\x12z\n" +
	"\x13MentalHealthHistory\x120.emotion_analytics.v1.MentalHealthHistoryRequest\x1a1.emotion_analytics.v1.MentalHealthHistoryResponse\x12z\n" +
	"\x13MentalHealthTrigger\x120.emotion_analytics.v1.MentalHealthTriggerRequest\x1a1.emotion_analytics.v1.MentalHealthTriggerResponse\x12t\n" +
	"\x11MentalHealthTrend\x12..emotion_analytics.v1.MentalHealthTrendRequest\x1a/.emotion_analytics.v1.MentalHealthTrendResponseB5Z3github.com/emotion-echo/shared/pkg/emotionanalyticsb\x06proto3"

var (
	file_metric_proto_rawDescOnce sync.Once
	file_metric_proto_rawDescData []byte
)

func file_metric_proto_rawDescGZIP() []byte {
	file_metric_proto_rawDescOnce.Do(func() {
		file_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)))
	})
	return file_metric_proto_rawDescData
}

var file_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_metric_proto_goTypes = []any{
	(*DateRange)(nil),                      // 0: emotion_analytics.v1.DateRange
	(*ChartDataPoint)(nil),                 // 1: emotion_analytics.v1.ChartDataPoint
	(*EmotionDistribution)(nil),            // 2: emotion_analytics.v1.EmotionDistribution
	(*UserBehaviorRequest)(nil),            // 3: emotion_analytics.v1.UserBehaviorRequest
	(*ReportsDailyRequest)(nil),            // 4: emotion_analytics.v1.ReportsDailyRequest
	(*ReportsDailyResponse)(nil),           // 5: emotion_analytics.v1.ReportsDailyResponse
	(*IntentCount)(nil),                    // 6: emotion_analytics.v1.IntentCount
	(*ReportsTrendRequest)(nil),            // 7: emotion_analytics.v1.ReportsTrendRequest
	(*ReportsTrendResponse)(nil),           // 8: emotion_analytics.v1.ReportsTrendResponse
	(*UserBehaviorDayNightResponse)(nil),   // 9: emotion_analytics.v1.UserBehaviorDayNightResponse
	(*UserBehaviorDepthResponse)(nil),      // 10: emotion_analytics.v1.UserBehaviorDepthResponse
	(*UserBehaviorFrequencyResponse)(nil),  // 11: emotion_analytics.v1.UserBehaviorFrequencyResponse
	(*MentalHealthAssessmentRequest)(nil),  // 12: emotion_analytics.v1.MentalHealthAssessmentRequest
	(*MentalHealthAssessmentResponse)(nil), // 13: emotion_analytics.v1.MentalHealthAssessmentResponse
	(*MentalHealthHistoryRequest)(nil),     // 14: emotion_analytics.v1.MentalHealthHistoryRequest
	(*MentalHealthHistoryResponse)(nil),    // 15: emotion_analytics.v1.MentalHealthHistoryResponse
	(*MentalHealthTriggerRequest)(nil),     // 16: emotion_analytics.v1.MentalHealthTriggerRequest
	(*MentalHealthTriggerResponse)(nil),    // 17: emotion_analytics.v1.MentalHealthTriggerResponse
	(*MentalHealthTrendRequest)(nil),       // 18: emotion_analytics.v1.MentalHealthTrendRequest
	(*MentalHealthTrendResponse)(nil),      // 19: emotion_analytics.v1.MentalHealthTrendResponse
}
var file_metric_proto_depIdxs = []int32{
	0,  // 0: emotion_analytics.v1.UserBehaviorRequest.date_range:type_name -> emotion_analytics.v1.DateRange
	2,  // 1: emotion_analytics.v1.ReportsDailyResponse.emotion_distribution:type_name -> emotion_analytics.v1.EmotionDistribution
	1,  // 2: emotion_analytics.v1.ReportsDailyResponse.emotion_trend:type_name -> emotion_analytics.v1.ChartDataPoint
	6,  // 3: emotion_analytics.v1.ReportsDailyResponse.intent_distribution:type_name -> emotion_analytics.v1.IntentCount
	0,  // 4: emotion_analytics.v1.ReportsTrendRequest.date_range:type_name -> emotion_analytics.v1.DateRange
	1,  // 5: emotion_analytics.v1.ReportsTrendResponse.data_points:type_name -> emotion_analytics.v1.ChartDataPoint
	6,  // 6: emotion_analytics.v1.ReportsTrendResponse.intent_distribution:type_name -> emotion_analytics.v1.IntentCount
	1,  // 7: emotion_analytics.v1.UserBehaviorDayNightResponse.active_hours:type_name -> emotion_analytics.v1.ChartDataPoint
	1,  // 8: emotion_analytics.v1.UserBehaviorDayNightResponse.message_hours:type_name -> emotion_analytics.v1.ChartDataPoint
	1,  // 9: emotion_analytics.v1.UserBehaviorDepthResponse.buckets:type_name -> emotion_analytics.v1.ChartDataPoint
	1,  // 10: emotion_analytics.v1.UserBehaviorFrequencyResponse.daily_active:type_name -> emotion_analytics.v1.ChartDataPoint
	2,  // 11: emotion_analytics.v1.MentalHealthAssessmentResponse.emotion_distribution:type_name -> emotion_analytics.v1.EmotionDistribution
	0,  // 12: emotion_analytics.v1.MentalHealthHistoryRequest.date_range:type_name -> emotion_analytics.v1.DateRange
	13, // 13: emotion_analytics.v1.MentalHealthHistoryResponse.records:type_name -> emotion_analytics.v1.MentalHealthAssessmentResponse
	0,  // 14: emotion_analytics.v1.MentalHealthTrendRequest.date_range:type_name -> emotion_analytics.v1.DateRange
	1,  // 15: emotion_analytics.v1.MentalHealthTrendResponse.score_trend:type_name -> emotion_analytics.v1.ChartDataPoint
	1,  // 16: emotion_analytics.v1.MentalHealthTrendResponse.risk_trend:type_name -> emotion_analytics.v1.ChartDataPoint
	4,  // 17: emotion_analytics.v1.AnalyticsService.ReportsDaily:input_type -> emotion_analytics.v1.ReportsDailyRequest
	7,  // 18: emotion_analytics.v1.AnalyticsService.ReportsTrend:input_type -> emotion_analytics.v1.ReportsTrendRequest
	3,  // 19: emotion_analytics.v1.AnalyticsService.UserBehaviorDayNight:input_type -> emotion_analytics.v1.UserBehaviorRequest
	3,  // 20: emotion_analytics.v1.AnalyticsService.UserBehaviorDepth:input_type -> emotion_analytics.v1.UserBehaviorRequest
	3,  // 21: emotion_analytics.v1.AnalyticsService.UserBehaviorFrequency:input_type -> emotion_analytics.v1.UserBehaviorRequest
	12, // 22: emotion_analytics.v1.AnalyticsService.MentalHealthAssessment:input_type -> emotion_analytics.v1.MentalHealthAssessmentRequest
	14, // 23: emotion_analytics.v1.AnalyticsService.MentalHealthHistory:input_type -> emotion_analytics.v1.MentalHealthHistoryRequest
	16, // 24: emotion_analytics.v1.AnalyticsService.MentalHealthTrigger:input_type -> emotion_analytics.v1.MentalHealthTriggerRequest
	18, // 25: emotion_analytics.v1.AnalyticsService.MentalHealthTrend:input_type -> emotion_analytics.v1.MentalHealthTrendRequest
	5,  // 26: emotion_analytics.v1.AnalyticsService.ReportsDaily:output_type -> emotion_analytics.v1.ReportsDailyResponse
	8,  // 27: emotion_analytics.v1.AnalyticsService.ReportsTrend:output_type -> emotion_analytics.v1.ReportsTrendResponse
	9,  // 28: emotion_analytics.v1.AnalyticsService.UserBehaviorDayNight:output_type -> emotion_analytics.v1.UserBehaviorDayNightResponse
	10, // 29: emotion_analytics.v1.AnalyticsService.UserBehaviorDepth:output_type -> emotion_analytics.v1.UserBehaviorDepthResponse
	11, // 30: emotion_analytics.v1.AnalyticsService.UserBehaviorFrequency:output_type -> emotion_analytics.v1.UserBehaviorFrequencyResponse
	13, // 31: emotion_analytics.v1.AnalyticsService.MentalHealthAssessment:output_type -> emotion_analytics.v1.MentalHealthAssessmentResponse
	15, // 32: emotion_analytics.v1.AnalyticsService.MentalHealthHistory:output_type -> emotion_analytics.v1.MentalHealthHistoryResponse
	17, // 33: emotion_analytics.v1.AnalyticsService.MentalHealthTrigger:output_type -> emotion_analytics.v1.MentalHealthTriggerResponse
	19, // 34: emotion_analytics.v1.AnalyticsService.MentalHealthTrend:output_type -> emotion_analytics.v1.MentalHealthTrendResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_metric_proto_init() }
func file_metric_proto_init() {
	if File_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metric_proto_goTypes,
		DependencyIndexes: file_metric_proto_depIdxs,
		MessageInfos:      file_metric_proto_msgTypes,
	}.Build()
	File_metric_proto = out.File
	file_metric_proto_goTypes = nil
	file_metric_proto_depIdxs = nil
}
