// proto/metric.proto
//
// Stage 62 PR-3.1: analytics-svc 暴露给 BFF 的 gRPC 接口（gRPC 渐进迁移 Phase 2）
//
// 背景（docs/plans/grpc-inter-service-migration.md §二 决策 A）：
//   analytics-svc HTTP :8893 保留给前端，内部 BFF 走 gRPC :8885
//   （feature flag: ANALYTICS_TRANSPORT=grpc|http）。
//
// 端点 1:1 对齐（emotion-echo-web-bff/internal/downstream/analytics.go）：
//   GET    /api/v1/reports/daily                      → ReportsDaily
//   GET    /api/v1/reports/trend                      → ReportsTrend
//   GET    /api/v1/user-behavior/day-night            → UserBehaviorDayNight
//   GET    /api/v1/user-behavior/depth                → UserBehaviorDepth
//   GET    /api/v1/user-behavior/frequency            → UserBehaviorFrequency
//   GET    /api/v1/mental-health/assessment           → MentalHealthAssessment
//   GET    /api/v1/mental-health/history                 → MentalHealthHistory
//   POST   /api/v1/mental-health/trigger              → MentalHealthTrigger
//   GET    /api/v1/mental-health/trend                → MentalHealthTrend
//
// 与 chat.proto / user.proto / agent.proto 区别：
//   - package: emotion_analytics.v1
//   - go_package: emotionanalytics
//   - 9 个 RPC（最大单一服务）
//
// 命名说明：
//   proto 文件名用 `metric.proto`（与 agent.proto 同理：避免与未来 `_service.proto`
//   命名冲突；go_package 保留 emotionanalytics 语义）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: metric.proto

package emotionanalytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_ReportsDaily_FullMethodName           = "/emotion_analytics.v1.AnalyticsService/ReportsDaily"
	AnalyticsService_ReportsTrend_FullMethodName           = "/emotion_analytics.v1.AnalyticsService/ReportsTrend"
	AnalyticsService_UserBehaviorDayNight_FullMethodName   = "/emotion_analytics.v1.AnalyticsService/UserBehaviorDayNight"
	AnalyticsService_UserBehaviorDepth_FullMethodName      = "/emotion_analytics.v1.AnalyticsService/UserBehaviorDepth"
	AnalyticsService_UserBehaviorFrequency_FullMethodName  = "/emotion_analytics.v1.AnalyticsService/UserBehaviorFrequency"
	AnalyticsService_MentalHealthAssessment_FullMethodName = "/emotion_analytics.v1.AnalyticsService/MentalHealthAssessment"
	AnalyticsService_MentalHealthHistory_FullMethodName    = "/emotion_analytics.v1.AnalyticsService/MentalHealthHistory"
	AnalyticsService_MentalHealthTrigger_FullMethodName    = "/emotion_analytics.v1.AnalyticsService/MentalHealthTrigger"
	AnalyticsService_MentalHealthTrend_FullMethodName      = "/emotion_analytics.v1.AnalyticsService/MentalHealthTrend"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # AnalyticsService 行为分析服务暴露给 BFF 的接口
//
// analytics-svc 同时跑 HTTP (:8893) + gRPC (:8885)。前端继续走 HTTP，
// 内部 BFF 走 gRPC。
type AnalyticsServiceClient interface {
	// ReportsDaily 每日情绪报告
	ReportsDaily(ctx context.Context, in *ReportsDailyRequest, opts ...grpc.CallOption) (*ReportsDailyResponse, error)
	// ReportsTrend 趋势报告（按日/周/月）
	ReportsTrend(ctx context.Context, in *ReportsTrendRequest, opts ...grpc.CallOption) (*ReportsTrendResponse, error)
	// UserBehaviorDayNight 用户行为按昼夜分布
	UserBehaviorDayNight(ctx context.Context, in *UserBehaviorRequest, opts ...grpc.CallOption) (*UserBehaviorDayNightResponse, error)
	// UserBehaviorDepth 用户行为深度（会话长度分布）
	UserBehaviorDepth(ctx context.Context, in *UserBehaviorRequest, opts ...grpc.CallOption) (*UserBehaviorDepthResponse, error)
	// UserBehaviorFrequency 用户行为频率（每日活跃天数）
	UserBehaviorFrequency(ctx context.Context, in *UserBehaviorRequest, opts ...grpc.CallOption) (*UserBehaviorFrequencyResponse, error)
	// MentalHealthAssessment 心理健康评估（综合日报）
	MentalHealthAssessment(ctx context.Context, in *MentalHealthAssessmentRequest, opts ...grpc.CallOption) (*MentalHealthAssessmentResponse, error)
	// MentalHealthHistory 心理健康历史
	MentalHealthHistory(ctx context.Context, in *MentalHealthHistoryRequest, opts ...grpc.CallOption) (*MentalHealthHistoryResponse, error)
	// MentalHealthTrigger 心理健康触发器（手动触发评估）
	MentalHealthTrigger(ctx context.Context, in *MentalHealthTriggerRequest, opts ...grpc.CallOption) (*MentalHealthTriggerResponse, error)
	// MentalHealthTrend 心理健康趋势
	MentalHealthTrend(ctx context.Context, in *MentalHealthTrendRequest, opts ...grpc.CallOption) (*MentalHealthTrendResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) ReportsDaily(ctx context.Context, in *ReportsDailyRequest, opts ...grpc.CallOption) (*ReportsDailyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportsDailyResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ReportsDaily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ReportsTrend(ctx context.Context, in *ReportsTrendRequest, opts ...grpc.CallOption) (*ReportsTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportsTrendResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ReportsTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) UserBehaviorDayNight(ctx context.Context, in *UserBehaviorRequest, opts ...grpc.CallOption) (*UserBehaviorDayNightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserBehaviorDayNightResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_UserBehaviorDayNight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) UserBehaviorDepth(ctx context.Context, in *UserBehaviorRequest, opts ...grpc.CallOption) (*UserBehaviorDepthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserBehaviorDepthResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_UserBehaviorDepth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) UserBehaviorFrequency(ctx context.Context, in *UserBehaviorRequest, opts ...grpc.CallOption) (*UserBehaviorFrequencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserBehaviorFrequencyResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_UserBehaviorFrequency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) MentalHealthAssessment(ctx context.Context, in *MentalHealthAssessmentRequest, opts ...grpc.CallOption) (*MentalHealthAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MentalHealthAssessmentResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_MentalHealthAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) MentalHealthHistory(ctx context.Context, in *MentalHealthHistoryRequest, opts ...grpc.CallOption) (*MentalHealthHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MentalHealthHistoryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_MentalHealthHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) MentalHealthTrigger(ctx context.Context, in *MentalHealthTriggerRequest, opts ...grpc.CallOption) (*MentalHealthTriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MentalHealthTriggerResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_MentalHealthTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) MentalHealthTrend(ctx context.Context, in *MentalHealthTrendRequest, opts ...grpc.CallOption) (*MentalHealthTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MentalHealthTrendResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_MentalHealthTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// # AnalyticsService 行为分析服务暴露给 BFF 的接口
//
// analytics-svc 同时跑 HTTP (:8893) + gRPC (:8885)。前端继续走 HTTP，
// 内部 BFF 走 gRPC。
type AnalyticsServiceServer interface {
	// ReportsDaily 每日情绪报告
	ReportsDaily(context.Context, *ReportsDailyRequest) (*ReportsDailyResponse, error)
	// ReportsTrend 趋势报告（按日/周/月）
	ReportsTrend(context.Context, *ReportsTrendRequest) (*ReportsTrendResponse, error)
	// UserBehaviorDayNight 用户行为按昼夜分布
	UserBehaviorDayNight(context.Context, *UserBehaviorRequest) (*UserBehaviorDayNightResponse, error)
	// UserBehaviorDepth 用户行为深度（会话长度分布）
	UserBehaviorDepth(context.Context, *UserBehaviorRequest) (*UserBehaviorDepthResponse, error)
	// UserBehaviorFrequency 用户行为频率（每日活跃天数）
	UserBehaviorFrequency(context.Context, *UserBehaviorRequest) (*UserBehaviorFrequencyResponse, error)
	// MentalHealthAssessment 心理健康评估（综合日报）
	MentalHealthAssessment(context.Context, *MentalHealthAssessmentRequest) (*MentalHealthAssessmentResponse, error)
	// MentalHealthHistory 心理健康历史
	MentalHealthHistory(context.Context, *MentalHealthHistoryRequest) (*MentalHealthHistoryResponse, error)
	// MentalHealthTrigger 心理健康触发器（手动触发评估）
	MentalHealthTrigger(context.Context, *MentalHealthTriggerRequest) (*MentalHealthTriggerResponse, error)
	// MentalHealthTrend 心理健康趋势
	MentalHealthTrend(context.Context, *MentalHealthTrendRequest) (*MentalHealthTrendResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) ReportsDaily(context.Context, *ReportsDailyRequest) (*ReportsDailyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportsDaily not implemented")
}
func (UnimplementedAnalyticsServiceServer) ReportsTrend(context.Context, *ReportsTrendRequest) (*ReportsTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportsTrend not implemented")
}
func (UnimplementedAnalyticsServiceServer) UserBehaviorDayNight(context.Context, *UserBehaviorRequest) (*UserBehaviorDayNightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserBehaviorDayNight not implemented")
}
func (UnimplementedAnalyticsServiceServer) UserBehaviorDepth(context.Context, *UserBehaviorRequest) (*UserBehaviorDepthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserBehaviorDepth not implemented")
}
func (UnimplementedAnalyticsServiceServer) UserBehaviorFrequency(context.Context, *UserBehaviorRequest) (*UserBehaviorFrequencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserBehaviorFrequency not implemented")
}
func (UnimplementedAnalyticsServiceServer) MentalHealthAssessment(context.Context, *MentalHealthAssessmentRequest) (*MentalHealthAssessmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MentalHealthAssessment not implemented")
}
func (UnimplementedAnalyticsServiceServer) MentalHealthHistory(context.Context, *MentalHealthHistoryRequest) (*MentalHealthHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MentalHealthHistory not implemented")
}
func (UnimplementedAnalyticsServiceServer) MentalHealthTrigger(context.Context, *MentalHealthTriggerRequest) (*MentalHealthTriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MentalHealthTrigger not implemented")
}
func (UnimplementedAnalyticsServiceServer) MentalHealthTrend(context.Context, *MentalHealthTrendRequest) (*MentalHealthTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MentalHealthTrend not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_ReportsDaily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportsDailyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ReportsDaily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ReportsDaily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ReportsDaily(ctx, req.(*ReportsDailyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ReportsTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportsTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ReportsTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ReportsTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ReportsTrend(ctx, req.(*ReportsTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_UserBehaviorDayNight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBehaviorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).UserBehaviorDayNight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_UserBehaviorDayNight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).UserBehaviorDayNight(ctx, req.(*UserBehaviorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_UserBehaviorDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBehaviorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).UserBehaviorDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_UserBehaviorDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).UserBehaviorDepth(ctx, req.(*UserBehaviorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_UserBehaviorFrequency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBehaviorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).UserBehaviorFrequency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_UserBehaviorFrequency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).UserBehaviorFrequency(ctx, req.(*UserBehaviorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_MentalHealthAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MentalHealthAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).MentalHealthAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_MentalHealthAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).MentalHealthAssessment(ctx, req.(*MentalHealthAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_MentalHealthHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MentalHealthHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).MentalHealthHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_MentalHealthHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).MentalHealthHistory(ctx, req.(*MentalHealthHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_MentalHealthTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MentalHealthTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).MentalHealthTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_MentalHealthTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).MentalHealthTrigger(ctx, req.(*MentalHealthTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_MentalHealthTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MentalHealthTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).MentalHealthTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_MentalHealthTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).MentalHealthTrend(ctx, req.(*MentalHealthTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportsDaily",
			Handler:    _AnalyticsService_ReportsDaily_Handler,
		},
		{
			MethodName: "ReportsTrend",
			Handler:    _AnalyticsService_ReportsTrend_Handler,
		},
		{
			MethodName: "UserBehaviorDayNight",
			Handler:    _AnalyticsService_UserBehaviorDayNight_Handler,
		},
		{
			MethodName: "UserBehaviorDepth",
			Handler:    _AnalyticsService_UserBehaviorDepth_Handler,
		},
		{
			MethodName: "UserBehaviorFrequency",
			Handler:    _AnalyticsService_UserBehaviorFrequency_Handler,
		},
		{
			MethodName: "MentalHealthAssessment",
			Handler:    _AnalyticsService_MentalHealthAssessment_Handler,
		},
		{
			MethodName: "MentalHealthHistory",
			Handler:    _AnalyticsService_MentalHealthHistory_Handler,
		},
		{
			MethodName: "MentalHealthTrigger",
			Handler:    _AnalyticsService_MentalHealthTrigger_Handler,
		},
		{
			MethodName: "MentalHealthTrend",
			Handler:    _AnalyticsService_MentalHealthTrend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metric.proto",
}
