apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-webhook
  namespace: {{ include "alertmanager.namespaceObservability" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-url: {{ .Values.webhook | default "https://dev-webhook-placeholder.invalid/alert" | quote }}