apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ include "alertmanager.namespaceObservability" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 9093 }}
      targetPort: http
      protocol: TCP