apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix.fullname" . }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
    - name: admin
      port: {{ .Values.adminPort }}
      targetPort: admin
    - name: prometheus
      port: {{ .Values.prometheusPort }}
      targetPort: prometheus
    - name: control
      port: 9092
      targetPort: control
    {{- if .Values.dashboard.enabled }}
    - name: dashboard
      port: {{ .Values.dashboardPort }}
      targetPort: dashboard
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "apisix.fullname" . }}
