// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: emotion_llm.proto

package emotionllm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalyzeRequest 单条消息的情绪分析请求
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_emotion_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AnalyzeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// AnalyzeResponse 单条消息的情绪分析响应
type AnalyzeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PrimaryEmotion string                 `protobuf:"bytes,2,opt,name=primary_emotion,json=primaryEmotion,proto3" json:"primary_emotion,omitempty"`   // happy/sad/anxious/angry/calm...
	SentimentScore float64                `protobuf:"fixed64,3,opt,name=sentiment_score,json=sentimentScore,proto3" json:"sentiment_score,omitempty"` // -1.0 ~ 1.0
	Confidence     float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`                               // 0.0 ~ 1.0
	Model          string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                                           // "gpt-4" / "keyword-fallback"
	RawResponse    string                 `protobuf:"bytes,6,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`            // 原始响应（调试用）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_emotion_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AnalyzeResponse) GetPrimaryEmotion() string {
	if x != nil {
		return x.PrimaryEmotion
	}
	return ""
}

func (x *AnalyzeResponse) GetSentimentScore() float64 {
	if x != nil {
		return x.SentimentScore
	}
	return 0
}

func (x *AnalyzeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnalyzeResponse) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

// AnalyzeBatchRequest 批量情绪分析请求
type AnalyzeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnalyzeRequest      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                 // 多条消息
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID（统一鉴权）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBatchRequest) Reset() {
	*x = AnalyzeBatchRequest{}
	mi := &file_emotion_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBatchRequest) ProtoMessage() {}

func (x *AnalyzeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBatchRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBatchRequest) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeBatchRequest) GetItems() []*AnalyzeRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AnalyzeBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_emotion_llm_proto protoreflect.FileDescriptor

const file_emotion_llm_proto_rawDesc = "" +
	"\n" +
	"\x11emotion_llm.proto\x12\x0eemotion_llm.v1\"\\\n" +
	"\x0eAnalyzeRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xdb\x01\n" +
	"\x0fAnalyzeResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fprimary_emotion\x18\x02 \x01(\tR\x0eprimaryEmotion\x12'\n" +
	"\x0fsentiment_score\x18\x03 \x01(\x01R\x0esentimentScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12!\n" +
	"\fraw_response\x18\x06 \x01(\tR\vrawResponse\"d\n" +
	"\x13AnalyzeBatchRequest\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.emotion_llm.v1.AnalyzeRequestR\x05items\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xb7\x01\n" +
	"\x11EmotionLLMService\x12J\n" +
	"\aAnalyze\x12\x1e.emotion_llm.v1.AnalyzeRequest\x1a\x1f.emotion_llm.v1.AnalyzeResponse\x12V\n" +
	"\fAnalyzeBatch\x12#.emotion_llm.v1.AnalyzeBatchRequest\x1a\x1f.emotion_llm.v1.AnalyzeResponse0\x01B/Z-github.com/emotion-echo/shared/pkg/emotionllmb\x06proto3"

var (
	file_emotion_llm_proto_rawDescOnce sync.Once
	file_emotion_llm_proto_rawDescData []byte
)

func file_emotion_llm_proto_rawDescGZIP() []byte {
	file_emotion_llm_proto_rawDescOnce.Do(func() {
		file_emotion_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emotion_llm_proto_rawDesc), len(file_emotion_llm_proto_rawDesc)))
	})
	return file_emotion_llm_proto_rawDescData
}

var file_emotion_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_emotion_llm_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),      // 0: emotion_llm.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),     // 1: emotion_llm.v1.AnalyzeResponse
	(*AnalyzeBatchRequest)(nil), // 2: emotion_llm.v1.AnalyzeBatchRequest
}
var file_emotion_llm_proto_depIdxs = []int32{
	0, // 0: emotion_llm.v1.AnalyzeBatchRequest.items:type_name -> emotion_llm.v1.AnalyzeRequest
	0, // 1: emotion_llm.v1.EmotionLLMService.Analyze:input_type -> emotion_llm.v1.AnalyzeRequest
	2, // 2: emotion_llm.v1.EmotionLLMService.AnalyzeBatch:input_type -> emotion_llm.v1.AnalyzeBatchRequest
	1, // 3: emotion_llm.v1.EmotionLLMService.Analyze:output_type -> emotion_llm.v1.AnalyzeResponse
	1, // 4: emotion_llm.v1.EmotionLLMService.AnalyzeBatch:output_type -> emotion_llm.v1.AnalyzeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_emotion_llm_proto_init() }
func file_emotion_llm_proto_init() {
	if File_emotion_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emotion_llm_proto_rawDesc), len(file_emotion_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emotion_llm_proto_goTypes,
		DependencyIndexes: file_emotion_llm_proto_depIdxs,
		MessageInfos:      file_emotion_llm_proto_msgTypes,
	}.Build()
	File_emotion_llm_proto = out.File
	file_emotion_llm_proto_goTypes = nil
	file_emotion_llm_proto_depIdxs = nil
}
