// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: emotion_llm.proto

package emotionllm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClassifyIntentRequest 意图分类请求
type ClassifyIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 待分类文本（通常为最后一条 user 消息）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyIntentRequest) Reset() {
	*x = ClassifyIntentRequest{}
	mi := &file_emotion_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyIntentRequest) ProtoMessage() {}

func (x *ClassifyIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyIntentRequest.ProtoReflect.Descriptor instead.
func (*ClassifyIntentRequest) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyIntentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// IntentResult 意图分类结果
type IntentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        string                 `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`           // 6 类之一；无法判定 → other
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 ~ 1.0（关键词命中强度）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentResult) Reset() {
	*x = IntentResult{}
	mi := &file_emotion_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentResult) ProtoMessage() {}

func (x *IntentResult) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentResult.ProtoReflect.Descriptor instead.
func (*IntentResult) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{1}
}

func (x *IntentResult) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *IntentResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// ChatMessage 对话消息（OpenAI role/content 语义）
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // system / user / assistant
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_emotion_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatCompletionRequest 对话请求
type ChatCompletionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Messages    []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Model       string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                           // 可选；空 = 服务端 env 默认
	Temperature float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`             // 可选；0 = 服务端默认
	MaxTokens   int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // 可选；0 = 不限制
	UserId      string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 审计/限流维度
	// Stage 82 PR-3a：true = 服务端对最后一条 user 消息做意图分类，
	// 按意图注入回复风格指令到 system prompt，并在首帧回带 intent
	WithIntent    bool `protobuf:"varint,6,opt,name=with_intent,json=withIntent,proto3" json:"with_intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_emotion_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{3}
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatCompletionRequest) GetWithIntent() bool {
	if x != nil {
		return x.WithIntent
	}
	return false
}

// ChatChunk 流式响应帧
type ChatChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeltaContent   string                 `protobuf:"bytes,1,opt,name=delta_content,json=deltaContent,proto3" json:"delta_content,omitempty"`       // 增量文本（OpenAI delta.content 语义）
	Done           bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`                                          // 结束帧（其后不再有帧）
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                         // 实际使用的模型（首帧携带；mock 时为 "mock"）
	FallbackReason string                 `protobuf:"bytes,4,opt,name=fallback_reason,json=fallbackReason,proto3" json:"fallback_reason,omitempty"` // 非空 = 本响应走了 mock 兜底（原因说明）
	Intent         string                 `protobuf:"bytes,5,opt,name=intent,proto3" json:"intent,omitempty"`                                       // Stage 82：意图分类结果（仅首帧携带；未启用 with_intent 时空）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_emotion_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{4}
}

func (x *ChatChunk) GetDeltaContent() string {
	if x != nil {
		return x.DeltaContent
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatChunk) GetFallbackReason() string {
	if x != nil {
		return x.FallbackReason
	}
	return ""
}

func (x *ChatChunk) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

// AnalyzeRequest 单条消息的情绪分析请求
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_emotion_llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AnalyzeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// AnalyzeResponse 单条消息的情绪分析响应
type AnalyzeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PrimaryEmotion string                 `protobuf:"bytes,2,opt,name=primary_emotion,json=primaryEmotion,proto3" json:"primary_emotion,omitempty"`   // happy/sad/anxious/angry/calm...
	SentimentScore float64                `protobuf:"fixed64,3,opt,name=sentiment_score,json=sentimentScore,proto3" json:"sentiment_score,omitempty"` // -1.0 ~ 1.0
	Confidence     float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`                               // 0.0 ~ 1.0
	Model          string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                                           // "gpt-4" / "keyword-fallback"
	RawResponse    string                 `protobuf:"bytes,6,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`            // 原始响应（调试用）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_emotion_llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyzeResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AnalyzeResponse) GetPrimaryEmotion() string {
	if x != nil {
		return x.PrimaryEmotion
	}
	return ""
}

func (x *AnalyzeResponse) GetSentimentScore() float64 {
	if x != nil {
		return x.SentimentScore
	}
	return 0
}

func (x *AnalyzeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnalyzeResponse) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

// AnalyzeBatchRequest 批量情绪分析请求
type AnalyzeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnalyzeRequest      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                 // 多条消息
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID（统一鉴权）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBatchRequest) Reset() {
	*x = AnalyzeBatchRequest{}
	mi := &file_emotion_llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBatchRequest) ProtoMessage() {}

func (x *AnalyzeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBatchRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBatchRequest) Descriptor() ([]byte, []int) {
	return file_emotion_llm_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeBatchRequest) GetItems() []*AnalyzeRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AnalyzeBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_emotion_llm_proto protoreflect.FileDescriptor

const file_emotion_llm_proto_rawDesc = "" +
	"\n" +
	"\x11emotion_llm.proto\x12\x0eemotion_llm.v1\"+\n" +
	"\x15ClassifyIntentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"F\n" +
	"\fIntentResult\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xe1\x01\n" +
	"\x15ChatCompletionRequest\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.emotion_llm.v1.ChatMessageR\bmessages\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1f\n" +
	"\vwith_intent\x18\x06 \x01(\bR\n" +
	"withIntent\"\x9b\x01\n" +
	"\tChatChunk\x12#\n" +
	"\rdelta_content\x18\x01 \x01(\tR\fdeltaContent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12'\n" +
	"\x0ffallback_reason\x18\x04 \x01(\tR\x0efallbackReason\x12\x16\n" +
	"\x06intent\x18\x05 \x01(\tR\x06intent\"\\\n" +
	"\x0eAnalyzeRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xdb\x01\n" +
	"\x0fAnalyzeResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fprimary_emotion\x18\x02 \x01(\tR\x0eprimaryEmotion\x12'\n" +
	"\x0fsentiment_score\x18\x03 \x01(\x01R\x0esentimentScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12!\n" +
	"\fraw_response\x18\x06 \x01(\tR\vrawResponse\"d\n" +
	"\x13AnalyzeBatchRequest\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.emotion_llm.v1.AnalyzeRequestR\x05items\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xe4\x02\n" +
	"\x11EmotionLLMService\x12J\n" +
	"\aAnalyze\x12\x1e.emotion_llm.v1.AnalyzeRequest\x1a\x1f.emotion_llm.v1.AnalyzeResponse\x12V\n" +
	"\fAnalyzeBatch\x12#.emotion_llm.v1.AnalyzeBatchRequest\x1a\x1f.emotion_llm.v1.AnalyzeResponse0\x01\x12T\n" +
	"\x0eChatCompletion\x12%.emotion_llm.v1.ChatCompletionRequest\x1a\x19.emotion_llm.v1.ChatChunk0\x01\x12U\n" +
	"\x0eClassifyIntent\x12%.emotion_llm.v1.ClassifyIntentRequest\x1a\x1c.emotion_llm.v1.IntentResultB/Z-github.com/emotion-echo/shared/pkg/emotionllmb\x06proto3"

var (
	file_emotion_llm_proto_rawDescOnce sync.Once
	file_emotion_llm_proto_rawDescData []byte
)

func file_emotion_llm_proto_rawDescGZIP() []byte {
	file_emotion_llm_proto_rawDescOnce.Do(func() {
		file_emotion_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emotion_llm_proto_rawDesc), len(file_emotion_llm_proto_rawDesc)))
	})
	return file_emotion_llm_proto_rawDescData
}

var file_emotion_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_emotion_llm_proto_goTypes = []any{
	(*ClassifyIntentRequest)(nil), // 0: emotion_llm.v1.ClassifyIntentRequest
	(*IntentResult)(nil),          // 1: emotion_llm.v1.IntentResult
	(*ChatMessage)(nil),           // 2: emotion_llm.v1.ChatMessage
	(*ChatCompletionRequest)(nil), // 3: emotion_llm.v1.ChatCompletionRequest
	(*ChatChunk)(nil),             // 4: emotion_llm.v1.ChatChunk
	(*AnalyzeRequest)(nil),        // 5: emotion_llm.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),       // 6: emotion_llm.v1.AnalyzeResponse
	(*AnalyzeBatchRequest)(nil),   // 7: emotion_llm.v1.AnalyzeBatchRequest
}
var file_emotion_llm_proto_depIdxs = []int32{
	2, // 0: emotion_llm.v1.ChatCompletionRequest.messages:type_name -> emotion_llm.v1.ChatMessage
	5, // 1: emotion_llm.v1.AnalyzeBatchRequest.items:type_name -> emotion_llm.v1.AnalyzeRequest
	5, // 2: emotion_llm.v1.EmotionLLMService.Analyze:input_type -> emotion_llm.v1.AnalyzeRequest
	7, // 3: emotion_llm.v1.EmotionLLMService.AnalyzeBatch:input_type -> emotion_llm.v1.AnalyzeBatchRequest
	3, // 4: emotion_llm.v1.EmotionLLMService.ChatCompletion:input_type -> emotion_llm.v1.ChatCompletionRequest
	0, // 5: emotion_llm.v1.EmotionLLMService.ClassifyIntent:input_type -> emotion_llm.v1.ClassifyIntentRequest
	6, // 6: emotion_llm.v1.EmotionLLMService.Analyze:output_type -> emotion_llm.v1.AnalyzeResponse
	6, // 7: emotion_llm.v1.EmotionLLMService.AnalyzeBatch:output_type -> emotion_llm.v1.AnalyzeResponse
	4, // 8: emotion_llm.v1.EmotionLLMService.ChatCompletion:output_type -> emotion_llm.v1.ChatChunk
	1, // 9: emotion_llm.v1.EmotionLLMService.ClassifyIntent:output_type -> emotion_llm.v1.IntentResult
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_emotion_llm_proto_init() }
func file_emotion_llm_proto_init() {
	if File_emotion_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emotion_llm_proto_rawDesc), len(file_emotion_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emotion_llm_proto_goTypes,
		DependencyIndexes: file_emotion_llm_proto_depIdxs,
		MessageInfos:      file_emotion_llm_proto_msgTypes,
	}.Build()
	File_emotion_llm_proto = out.File
	file_emotion_llm_proto_goTypes = nil
	file_emotion_llm_proto_depIdxs = nil
}
