// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: emotion_llm.proto

package emotionllm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmotionLLMService_Analyze_FullMethodName        = "/emotion_llm.v1.EmotionLLMService/Analyze"
	EmotionLLMService_AnalyzeBatch_FullMethodName   = "/emotion_llm.v1.EmotionLLMService/AnalyzeBatch"
	EmotionLLMService_ChatCompletion_FullMethodName = "/emotion_llm.v1.EmotionLLMService/ChatCompletion"
)

// EmotionLLMServiceClient is the client API for EmotionLLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # EmotionLLMService 是 ai-svc 调用 emotion-llm-service 的契约
//
// 之前是 HTTP（ai-svc.HTTPAnalyzer → POST /analyze）。
// 升级为 gRPC 后更高效（HTTP/2 streaming + protobuf 强契约）。
type EmotionLLMServiceClient interface {
	// Analyze 单条消息情绪分析
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// AnalyzeBatch 批量分析（server stream，Stage 16）
	//
	// 适用：AI 一次推多条消息，server 流式返回每条结果（首字节延迟低）
	AnalyzeBatch(ctx context.Context, in *AnalyzeBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyzeResponse], error)
	// ChatCompletion 流式对话（Stage 80 · llm-chat-real-pipeline PR-1）
	//
	// OpenAI chat.completions 兼容语义：消息数组入、增量 chunk 流出。
	// 上游 LLM 由 env 决定（LLM_BASE_URL/LLM_API_KEY/LLM_MODEL，DeepSeek 等
	// OpenAI 兼容端点）；无 key 或上游失败时降级内置 mock 文案（fallback_reason 非空），
	// 保证 CI / 离线 demo 全链路可跑（§契约 6 同款哲学）。
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
}

type emotionLLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionLLMServiceClient(cc grpc.ClientConnInterface) EmotionLLMServiceClient {
	return &emotionLLMServiceClient{cc}
}

func (c *emotionLLMServiceClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, EmotionLLMService_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionLLMServiceClient) AnalyzeBatch(ctx context.Context, in *AnalyzeBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyzeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmotionLLMService_ServiceDesc.Streams[0], EmotionLLMService_AnalyzeBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeBatchRequest, AnalyzeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmotionLLMService_AnalyzeBatchClient = grpc.ServerStreamingClient[AnalyzeResponse]

func (c *emotionLLMServiceClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmotionLLMService_ServiceDesc.Streams[1], EmotionLLMService_ChatCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmotionLLMService_ChatCompletionClient = grpc.ServerStreamingClient[ChatChunk]

// EmotionLLMServiceServer is the server API for EmotionLLMService service.
// All implementations must embed UnimplementedEmotionLLMServiceServer
// for forward compatibility.
//
// # EmotionLLMService 是 ai-svc 调用 emotion-llm-service 的契约
//
// 之前是 HTTP（ai-svc.HTTPAnalyzer → POST /analyze）。
// 升级为 gRPC 后更高效（HTTP/2 streaming + protobuf 强契约）。
type EmotionLLMServiceServer interface {
	// Analyze 单条消息情绪分析
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// AnalyzeBatch 批量分析（server stream，Stage 16）
	//
	// 适用：AI 一次推多条消息，server 流式返回每条结果（首字节延迟低）
	AnalyzeBatch(*AnalyzeBatchRequest, grpc.ServerStreamingServer[AnalyzeResponse]) error
	// ChatCompletion 流式对话（Stage 80 · llm-chat-real-pipeline PR-1）
	//
	// OpenAI chat.completions 兼容语义：消息数组入、增量 chunk 流出。
	// 上游 LLM 由 env 决定（LLM_BASE_URL/LLM_API_KEY/LLM_MODEL，DeepSeek 等
	// OpenAI 兼容端点）；无 key 或上游失败时降级内置 mock 文案（fallback_reason 非空），
	// 保证 CI / 离线 demo 全链路可跑（§契约 6 同款哲学）。
	ChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatChunk]) error
	mustEmbedUnimplementedEmotionLLMServiceServer()
}

// UnimplementedEmotionLLMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionLLMServiceServer struct{}

func (UnimplementedEmotionLLMServiceServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedEmotionLLMServiceServer) AnalyzeBatch(*AnalyzeBatchRequest, grpc.ServerStreamingServer[AnalyzeResponse]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeBatch not implemented")
}
func (UnimplementedEmotionLLMServiceServer) ChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedEmotionLLMServiceServer) mustEmbedUnimplementedEmotionLLMServiceServer() {}
func (UnimplementedEmotionLLMServiceServer) testEmbeddedByValue()                           {}

// UnsafeEmotionLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionLLMServiceServer will
// result in compilation errors.
type UnsafeEmotionLLMServiceServer interface {
	mustEmbedUnimplementedEmotionLLMServiceServer()
}

func RegisterEmotionLLMServiceServer(s grpc.ServiceRegistrar, srv EmotionLLMServiceServer) {
	// If the following call panics, it indicates UnimplementedEmotionLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionLLMService_ServiceDesc, srv)
}

func _EmotionLLMService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionLLMServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionLLMService_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionLLMServiceServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionLLMService_AnalyzeBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzeBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmotionLLMServiceServer).AnalyzeBatch(m, &grpc.GenericServerStream[AnalyzeBatchRequest, AnalyzeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmotionLLMService_AnalyzeBatchServer = grpc.ServerStreamingServer[AnalyzeResponse]

func _EmotionLLMService_ChatCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmotionLLMServiceServer).ChatCompletion(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmotionLLMService_ChatCompletionServer = grpc.ServerStreamingServer[ChatChunk]

// EmotionLLMService_ServiceDesc is the grpc.ServiceDesc for EmotionLLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionLLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_llm.v1.EmotionLLMService",
	HandlerType: (*EmotionLLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _EmotionLLMService_Analyze_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeBatch",
			Handler:       _EmotionLLMService_AnalyzeBatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChatCompletion",
			Handler:       _EmotionLLMService_ChatCompletion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emotion_llm.proto",
}
