// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type EmotionView struct {
	Id             int64   `json:"id"`
	MessageId      int64   `json:"messageId"`
	ConversationId int64   `json:"conversationId"`
	UserId         int64   `json:"userId"`
	PrimaryEmotion string  `json:"primaryEmotion"`
	SentimentScore float64 `json:"sentimentScore"`
	Confidence     float64 `json:"confidence"`
	Model          string  `json:"model"`
	CreatedAt      int64   `json:"createdAt"`
}

type GetEmotionByMessageReq struct {
	MessageId int64 `path:"messageId"`
}

type GetEmotionByMessageResp struct {
	Emotion EmotionView `json:"emotion"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Time    int64  `json:"time"`
	Service string `json:"service"`
	Version string `json:"version"`
	DbOK    bool   `json:"dbOk"`
}

type ListEmotionByConversationReq struct {
	ConversationId int64 `path:"conversationId"`
}

type ListEmotionByConversationResp struct {
	Emotions []EmotionView `json:"emotions"`
}
