apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ee-data
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}